```{r}
#| echo: false

if (file.exists(table_dir)) {
  # Load in rda files created by:
  # r4ss::table_exec_summary
  # r4ss::table_pars
  # r4ss::table_parcounts
  
  all_files <- list.files(table_dir)
  all_rda_files <- all_files[grep(".rda", all_files)]
  for (a in 1:length(all_rda_files)) {
    load(file.path(table_dir, all_rda_files[a]))
  }
  
  catches_es_table <- catches_es$table
  catches_es_cap <- catches_es$cap
  rm(catches_es)
  
  ssb_es_table <- ssb_es$table
  ssb_es_cap <- ssb_es$cap
  rm(ssb_es)
  
  spr_es_table <- spr_es$table
  spr_es_cap <- spr_es$cap
  rm(spr_es)
  
  recr_es_table <- recr_es$table
  recr_es_cap <- recr_es$cap
  rm(recr_es)
  
  reference_points_table <- reference_points$table
  reference_points_cap <- reference_points$cap
  rm(reference_points)
  
  recent_management_table <- recent_management$table
  recent_management_cap <- recent_management$cap
  rm(recent_management)
    
  projections_table <- projections$table
  projections_cap <- projections$cap
  rm(projections)
  
  compweight_table <- table_compweight$table
  compweight_cap <- table_compweight$cap
  rm(table_compweight)
  
  config_table <- table_config$table
  config_cap <- table_config$cap
  rm(table_config)
  
  parcount_table <- table_parcounts$table
  parcount_cap <- table_parcounts$cap
  rm(table_parcounts)
  
  par_table <- table_pars$table
  par_cap <- table_pars$cap
  rm(table_pars)
  
  eval_tables <- TRUE
} else {
  eval_tables <- FALSE
}

```


```{r}
#| echo: false

# Special modification to the management and projection tables to add quantities
# from a sourced csv file in the skeleton r chunk.
  recent_management_table[, "OFL (mt)"] <- cw_harvest_spex |>
    dplyr::filter(SPECIFICATION_TYPE == "OFL", YEAR %in% es_10_years) |>
    dplyr::arrange(YEAR) |>
    dplyr::select(VAL)
  recent_management_table[, "ABC (mt)"] <- cw_harvest_spex |>
    dplyr::filter(SPECIFICATION_TYPE == "ABC", YEAR %in% es_10_years) |>
    dplyr::arrange(YEAR) |>
    dplyr::select(VAL)
  recent_management_table[, "ACL (mt)"] <- cw_harvest_spex |>
    dplyr::filter(SPECIFICATION_TYPE == "ACL", YEAR %in% es_10_years) |>
    dplyr::arrange(YEAR) |>
    dplyr::select(VAL)

  projections_table[1:2, "Adopted OFL (mt)"] <- cw_harvest_spex |>
    dplyr::filter(SPECIFICATION_TYPE == "OFL", YEAR >= end_year) |>
    dplyr::arrange(YEAR) |>
    dplyr::select(VAL)
  projections_table[1:2, "Adopted ACL (mt)"] <- cw_harvest_spex |>
    dplyr::filter(SPECIFICATION_TYPE == "ACL", YEAR >= end_year) |>
    dplyr::arrange(YEAR) |>
    dplyr::select(VAL)
  
  all_files <- list.files(here::here("data"))
  all_rda_files <- all_files[grep(".rda", all_files)]
  for (a in 1:length(all_rda_files)) {
    load(here::here("data", all_rda_files[a]))
  }
  
  wcgbt_catch <- data_survey_catch$nwfsc_combo |>
  dplyr::mutate(
    positive = dplyr::case_when(total_catch_numbers > 0 ~ 1, .default = 0),
    state = dplyr::case_when(Latitude_dd > 46.25 ~ "WA", 
                             Latitude_dd < 36.0 ~ "SCA", 
                             Latitude_dd >= 36.0 & Latitude_dd < 42.0 ~ "NCA",
                             .default = "OR"))
  wcgbt_bio <- data_survey_bio$nwfsc_combo

```
