
# Stock Assessment Summary {-}

At the beginning of `r end_year`, the population size of mature female fish (spawning output) is estimated to be `r sb_final` metric tons (mt), and overall stock status (i.e., relative spawning output compared to unfished) is estimated to be `r depl_final*100`%. The total population (mature and immature fish) is estimated to be sharply increasing in recent years (nearly doubling in size since 2020) from multiple strong cohorts (e.g., recruitment) occurring in 2016, 2020, 2021, and 2023. The projected coastwide Overfishing Limit (OFL) and Acceptable Biological Catch (ABC) in 2027 are 14,935 mt and 13,965 mt, respectively. The projected coastwide OFL and ABC in 2028 are 16,240 mt and 15,103 mt, respectively. 

This assessment includes all available data on catches (landings and discards), an updated index of abundance from the Northwest Fisheries Science Center West Coast Groundfish Bottom Trawl Survey (WCGBTS) from 2003--2024, all available fishery and survey ages deemed representative through 2024, and empirical weight-at-age data to empirically track changes in mean growth over time and space.

The 2025 assessment estimates the stock status of sablefish to be lower than what was projected by the 2023 assessment, with the population below the management limit of 40% and in the precautionary zone until 2027 when stock status is projected to be greater than 40%. The projected ABC in 2027 is more than double the 2024 removals but approximately 35% lower than the projected removals in 2025--2026. However, the overall scale of the population (*SB~0~*) increased by 18% in this assessment compared to the 2023 assessment.

*Why is this assessment different from the 2023 assessment?*

This assessment includes five primary improvements and changes in the model relative to the 2023 update assessment.  This includes two major data improvements: (1) the identification and use of additional historical ages collected from the commercial fishery between 1983--2000, primarily collected in Oregon; and (2) the use of an improved and more transparent approach to estimate mortality of discarded fish by the commercial fishery based upon available data collected across fishery sectors. Several major model structure improvements were also made to better represent sablefish biological processes off the West Coast. The assessment model moved to a strict (3) data driven approach to estimate annual recruitments with greater flexibility in the model to estimate low and high recruitment years. The assessment model switched from estimating a static growth function for each sex to (4) the use of empirical weight-at-age data to account for variable growth by age, sex, year, and area across the West Coast. Additionally, (5) the shape of the selectivity function for the WCGBTS was updated based upon data from the survey. The selectivity for the survey was estimated to be at or near full selectivity for age-1 and older sablefish. The WCGBTS is believed to consistently and representatively sample sablefish well, covering a large majority of their habitat off the West Coast. Many other data and model refinements were completed for this assessment. 