
\setlength{\parskip}{5mm plus1mm minus1mm}
\pagenumbering{arabic}
\setcounter{page}{1}
\setcounter{section}{0}
\renewcommand{\thefigure}{\arabic{figure}}
\renewcommand{\thetable}{\arabic{table}}
\setcounter{table}{0}
\setcounter{figure}{0}

# Introduction

## Stock Description

`r Spp` (*Anoplopoma fimbria*, also known as black cod) are distributed in the northeastern Pacific Ocean from the southern tip of Baja California northward to the north-central Bering Sea and in the northwestern Pacific Ocean from Kamchatka southward to the northeastern coast of Japan [@hart_pacific_1973; @eschmeyer_field_1983]. U.S. West Coast `r spp` are modeled as a single stock. Thus, this stock assessment does not explicitly account for movement between offshore sea mounts [@shaw_movement_1997; @morita_sex_2012; @hanselman_move_2015], regions to the north or south of the U.S. west coast, or to the western Pacific [@fujioka_description_1988; @heifetz_movement_1991; @hanselman_move_2015].

While previous analyses suggests the existence of several stocks of `r spp` in the eastern Pacific Ocean that are largely delineated by management boundaries (@shirripa_sablefish_2007; and earlier assessments), more recent genetic analyses found that `r spp` in the northeastern Pacific Ocean are a single panmictic population [@jasonowicz_love_2017]. Additional support for a panmictic population stems from tag recoveries that show `r spp` move across international boundaries, including regions currently used for management [@hanselman_move_2015; @sogard_patterns_2017; @kapur_tag_2025]. Despite generally similar movement estimates between the U.S. West Coast and British Columbia, a net change in demography may still be present due to differences in area-specific population sizes [@kapur_range_2024; @kapur_tag_2025]. Analyses of length-at-age data has found spatial variation in von Bertalanffy growth parameters across the northeastern Pacific Ocean [@mcdevitt_status_1987; @echave_interdecadal_2012; @head_maturity_2014; @gertseva_spatial_2017; @kapur_oceanographic_2020]. While geographic break points at approximately (1) 36$^\circ$ N. latitude between Point Conception and Monterey, California at the start of the southern California Bight and (2) 50$^\circ$ N. latitude where the North Pacific Current bifurcates suggest zones of growth variation, generally with increasing maximum body size and decreasing growth rates with increasing latitude, they do not indicate regions with separate populations.

Smaller `r spp` are generally found in shallower waters, but the demographics appears to be fully mixed (adult and juvenile) near the shelf-slope break (i.e., 100--300 m). Beyond the shelf-slope break, the adult population is dominated by older individuals [@methot_assessment_1994] and younger fish become increasingly rare. Fish in the deepest areas sampled tend to be the oldest individuals, but not the largest individuals, suggesting that age rather than size dictates depth distribution. However, the interaction between environmental conditions and seasonal movements that produce an increase in age with depth are largely unknown. The stock is distributed beyond the greatest depth sampled by any of the surveys and beyond the deepest commercial fishing areas. Research in these deeper habitats occupied by `r spp` is potentially difficult because they extend across the boundary of the exclusive economic zone and sea mounts and ridges around the Pacific. There are relatively fewer `r spp` in the Puget Sound and the Strait of Georgia than in coastal U.S. waters. Therefore, connectivity among these areas and the open coast is likely of less importance to this stock assessment than movement along the coast.

## Life History

@tolimieri_oceanographic_2018 provide a thorough review of the literature on spawning and early life history of `r spp` in the California Current. Briefly, `r spp` off the U.S. West Coast exhibit a protracted spawning period from December through March, with peak in February [@guzman_reproductive_2017]. This winter-time spawning may result in reduced availability to the commercial fishery during the winter months. Spawning occurs along the continental shelf-slope break in waters deeper than 300 m. Eggs (~2.1 mm in diameter) are buoyant and rise in the water column before hatching and sinking to deeper waters. Pelagic juveniles are present in off-shore surface waters and settle to the benthos as age-0 recruits during the late summer to fall, with most newly settled fish at depths of less than 250 m. 

`r Spp` reach full size and maturity in their first decade of life, reaching nearly asymptotic size and beginning to mature between 4-7 years. Female `r spp` generally reach larger sizes than males. However, the sex-ratio tends to be skewed toward males at the oldest ages implying either higher fishing pressure on females compared to males, lower natural mortality rate for males relative to females, or potentially a combination of both sex-specific longevity and selectivity. The oldest `r spp` observed off the West Coast in available data was captured in 2006 off Washington and aged (with observation error) at 102 years. 

Adult `r spp` are fast-swimming and capable of feeding on a diverse array of prey species including fishes, cephalopods, and crustaceans [@low_sablefish_1976]. The cohabitation of adult and juvenile `r spp` may result in some cannibalism, and large changes in predator biomass could have a feedback on juvenile survival and, therefore, stock productivity.

## Ecosystem Considerations

The sablefish \gls{cva} suggests that processes affecting recruitment are sensitive to climatic and, therefore, oceanic drivers [@mcclure_2023_vulnerability]. Given high climate vulnerability, changes in the abundance, productivity, and spatial distribution of sablefish are likely, and these changes are likely to impact fishing fleets and communities because of the high value of this fishery. The \gls{cva} also suggests that sablefish are likely to shift their distribution in response to climate variability.

The sablefish stock has experienced latitudinal shifts in the center of the distribution of stock biomass within the California Current, which has affected fishing opportunities to individual ports [@selden_2019]. The population centroid shifted to the north from 1980 to 1992 then south by 2013. More recently, the distribution of stock biomass shifted north, illustrated by an increase in \gls{s-wcgbt} biomass estimates in the north.

Strong coast-wide recruitment appears to be associated with good recruitment north of Cape Mendocino (~ 40$^\circ$ N. latitude). Modeling work shows that strong recruitment is correlated with transport and temperature in the northern portion (40$^\circ$--48$^\circ$ N. latitude) of the U.S. West Coast, specifically with the northern transport of yolk-sac larvae [@tolimieri2018]. A re-analysis of the relationship between sea level and recruitment found that variation around the stock-recruitment curve was negatively correlated with sea level north of Cape Mendocino. The 2019 assessment of sablefish included a sea surface height index within the model to inform historical and recent recruitment [@haltuch_status_2019]. This assessment includes a revised recruitment index that account for a number of oceanographic and ecosystem that appear to be correlated with sablefish recruitment in recent years (see Section \ref{rec-index-data} for additional information).

Age-0 sablefish captured by the \gls{s-wcgbt} were most abundant in shelf and upper-slope waters around San Francisco Bay and from Cape Mendocino to the mouth of the Columbia River. The abundance of age-0 recruits varied through time with peaks in recruitment in 2008, 2013, 2016, 2020, 2021, and 2023. However, most strong recruitment years were associated with high recruitment north of Cape Mendocino. Recent modeling work suggests that strong age-0 recruitment is associated, in part, with the northerly transport of yolk-sac larvae at depths between 1,000--1,200 meters (m) [@tolimieri2018], which may lead to better overlap between feeding larvae and copepod prey than when the larvae transport is not as defined.


## Fishery Description

Historical `r spp` landings, beginning in 1890, have been reconstructed by the states (Washington, Oregon, and California) using a variety of sources. Generally, historical `r spp` landings were more reliable than those for many other groundfish species because of their consistent species-level identification. While `r spp` landings were recorded back to the beginning of the 20th century, appreciable quantities were not landed until 1916--1919, with landings remaining below 5,000 metric tons (mt) through the late 1960s. Landings prior to 1960 were primarily harvested by hook-and-line gear. 

The `r spp` fishery increased dramatically during the 1970s, first from a combination of foreign vessels [@lynde_historical_1986; @mcdevitt_status_1987], followed by an increase in the domestic fleet. Increases correspond to the introduction of a pot fishery followed by an increase in the catch coming from the trawl sector, with only minor increases in the hook-and-line sector until the mid-1980s, after the peak removals from the other sectors. Large catches by foreign vessels, fishing pot gear, resulted in the large removals of over 25,000 mt in 1976 and 1979 from U.S. West Coast waters. A rapid rise in domestic pot and trawl landings followed these peak removals, with landings in the 1980s slowly declining from around 19,000 mt in 1982 to ~9,000 mt in 1990. The decline in domestic landings through the 1980s was likely due to a combination of declining stock size, reduced Asian-market strength, and increasing fishery regulations. During the most recent decade, annual landings have remained below 6,500 mt, divided approximately 43 percent by hook-and-line, 26 percent by pot, and 30 percent by trawl gear during the last ten years. 

An \gls{ifq} program was implemented off the U.S. West Coast in 2011. Sablefish are targeted by \gls{ifq} vessels using varying gear types. Gear switching within the \gls{ifq} fishery increased after the implementation of the program, leading to concerns about utilization of the trawl allocation for `r spp` north of 36$^{\circ}$ N. latitude. The majority of landings by vessels participating in gear switching was `r spp`.  At the April 2024 meeting, the \gls{pfmc}, took final action to limit gear switching in years when `r spp` \gls{acl} for the area north of 36$^{\circ}$ N. latitude is below 6,000 mt. 

In 2024, the ex-vessel revenue of the `r spp` fishery was estimated at 13.5 million dollars, the lowest in available data starting in 2005 (pers. comm., E. Steiner, \gls{nwfsc}). Since 2005, the ex-vessel revenue peaked 2011 at 61.5 million dollars and has generally had a decreasing trend since 2017.


## Management History and Performance

From the early 1900s to the early 1980s, management of the `r spp` fishery was the responsibility of the individual coastal states (California, Oregon, and Washington). Since the adoption of the Groundfish \gls{fmp} by the \gls{pfmc} in 1982, responsibility has rested with the federal government and the \gls{pfmc}. From 1977 to the mid-1980s, U.S. commercial fishermen took advantage of their newly protected fishing grounds (i.e., the enactment of the Fishery Conservation and Management Act, which occurred in in 1976, later to be renamed Magnuson Stevens Fishery Conservation and Management Act) recording high catches of `r spp` to meet the demands of flourishing export (primarily Asian countries) and domestic markets.

The first coastwide regulations off the U.S. Pacific Coast for the `r spp` fishery were implemented as trip limits in October 1982, followed by a rich history of management via seasons, size-limits, trip-limits, and a complex permit system. Beginning in 1983, additional trip limits were imposed on landings of `r spp` less than 22 inches in length, considered incidental catch. In 1987, allocations between the trawl and non-trawl fleets were implemented.

Beginning in the late-1980s, the fixed-gear `r spp` fishery was managed as a `derby' fishery, characterized by increasing reductions in season lengths. In 1991, the fully open season lasted seven weeks, from April 1 through May 23. In 1992, approximately 1,300 mt were landed under early season trip limits of up to 1,500 pounds per day, and the fully open season lasted from May 12 through May 26. In 1993, there was a 250 pounds per day trip limit prior to the open season which extended from May 12 through June 1. In 1994, the fully open season was shorted to May 15 through June 3. In 1995, the open season lasted one week, from August 3 to August 13. The open season spanned only six days in 1996, from September 1 to September 6. In 1997, nine days (August 25 to September 3) were set aside for the open season, with a mop-up period from October 1-15. In the more recent period, the Limited Entry Fixed Gear sector has been managed primarily through the use of tiered cumulative limits (allocated on the basis of historical landings) which can be landed throughout the 7-month season. The remaining open-access fishery and some limited-entry non-trawl vessels are allowed to make smaller landings that are subject to daily/weekly limits and two-month cumulative caps.

In 2002--2003, the \gls{pfmc} enacted area closures, called \gls{rca}, in specific areas along the West Coast to support rebuilding of overfished rockfish species. These areas were closed to fishing with certain gear types with the boundaries of the \gls{rca} differing depending upon the fishing gear being used. At the start of 2024, a significant portion of \gls{rca} had restrictions were lifted for non-trawl commercial and recreational vessels targeting groundfish. 

`r Spp` are harvested by the trawl fishery in association with a variety of other species that are distributed to domestic and foreign markets. Prior to 2011 with the introduction of the \gls{ifq}, the trawl fishery was managed primarily through the use of trip limits. These evolved from simple per-trip limits in the 1980s to cumulative periodic (monthly or bi-monthly) limits by the mid-1990s. Since 2011, \gls{ifq} vessels operate using allocated quota pounds while vessels operating in Limited Entry and Open Access sector are still managed using trip limits that restrict landings per week and per two month periods. A list of select management changes since 2010 is provided in Section \ref{ref-man-history}.

Currently, \gls{pfmc} manages `r spp` off the U.S. West using two area-specific \gls{acl} north and south of 36$^\circ$ N. latitude. Management splits the coastwide \gls{abc} based on the most recent five year average of estimation biomass from the \gls{s-wcgbt}. 


## Fisheries off Canada and Alaska

Exploring regional trends in population dynamics can be a useful way to elicit patterns and gain insights, particularly for stocks such as `r spp` that are connected over long distances spanning multiple management jurisdictions. Landings data, population dynamic trends, and stock status are available in the most recent `r spp` stock assessments for the U.S. West Coast [@johnson_status_2023], British Columbia [@DFO2023], and Alaska [@Goethel_assess_2024].

Total landings of `r spp` has changed considerably over time in all three stock assessments. Similarly to the U.S. West Coast, `r spp` fisheries in Alaska and British Columbia waters began in the late 1800s, with generally low catches until after World War II. Foreign fisheries began exploiting `r spp` in the northeastern Pacific Ocean during the late 1950s in the Bering Sea leading to rapidly increasing catches in the region through the 1980s. While all three areas showed a general decline in catch during the 1990s to 2000s, there has been a slight uptick in catch in recent years especially in Alaska and British Columbia. For comparison, catch in 2021 was nearly 22,000 mt in Alaska, 2,400 mt in British Columbia, and 5,000 mt along the U.S. West Coast. Landings peaked during the 1970s in Alaska (> 50,000 mt), British Columbia (> 7,000 mt), and the U.S. West Coast (> 25,000 mt). The `r spp` fishery in the waters off British Columbia primarily uses pots, with a lesser amount landed using long lines and trawls. Historically, Alaskan landings have been much larger than those off the U.S. West Coast.

Spawning output in Alaska and British Columbia have generally declined until the late 2010s, but are now increasing quite rapidly. The U.S. West Coast population generally declined from the 1970s to the early 2000s. The population was then relatively stable through the late 2010s, before increasing rapidly in recent years due to good recruitment. In general, there are periods over time that coincide with above average recruitment across all three assessment areas. In particular, there has been several strong recruitment events in all three areas over the last 10 years. The three largest recruitment events (all scaled to age-0) were similar in Alaska (2016, 2017, and 2019 cohorts), British Columbia (2015, 2016, and 2017), and along the U.S. West Coast (2016, 2020, and 2021). 

Overall stock status (also referred to as depletion, relative spawning output, or fraction unfished) is estimated to have been 67 percent of equilibrium spawning output in Alaska (in 2024), 54 percent in British Columbia (2022), and `r depl_final*100` percent for the U.S. West Coast area in this assessment. Status in all three regions can be generalized to indicate that overfishing is not occurring and the stocks are not overfished. The stock in Alaska and British Columbia has been above fishing-based reference levels and below biomass-based reference levels at one point or another during the time series (@fig-reg-kobe). However, recent strong recruitment events are now contributing to spawning output, which is driving the trend of increasing stock status measures over recent years in all three areas.
