# Data

A description of each data source used in this assessment (@fig-data) is provided below.

## Fishery-Dependent data

### Landings {#landings}

Landings for `r spp` contains various historical landings reconstructions, historical foreign fishery catch data, commercial domestic landings data extracted from \gls{pacfin} on February, 25, 2025,  Pacific hake at-sea fishery catch estimates (provided by Vanessa Tuttle, \gls{nwfsc}, \gls{noaa}), and recreational landings data extracted from \gls{recfin} on February, 28, 2025. The landings used in this assessment are shown in @fig-landings and @tbl-landings. 

The model includes six fishery fleets: 1) trawl, 2) hook-and-line, 3) pot, 4) trawl discards, 5) hook-and-line discards, and 6) pot discards. The trawl fleet includes mortality from the domestic historical (pre-1981 in California and Washington, pre-1987 in Oregon) and current landings available in \gls{pacfin}, estimated foreign trawl catch, and  Pacific hake at-sea fishery total mortality estimates. The hook-and-line fleet includes mortality from the domestic historical (pre-1981 in California and Washington, pre-1987 in Oregon) and current landings available in \gls{pacfin}, estimated foreign hook-and-line total mortality, and recreational fisheries total mortality estimates. The pot fleet includes mortality from the domestic historical (pre-1981 in California and Washington, pre-1987 in Oregon) and current landings available in \gls{pacfin} and estimated foreign pot catch. The discard fleets are composed of estimated discards for the domestic historical and current commercial landings using available information on discard rates with gear-specific discard mortality rates.

For the state of California, commercial landings between 1900 and 1931 were calculated following the approach used in the 2011 and 2019 assessments for `r spp` where 1916--1931 landings estimates were available from published California Department of Fish and Game Bulletins back, 1908 to 1916 were based on Fisheries statistics of the U.S., published by the U.S. Fish Commission, and 1900--1907 landings were were extrapolated linearly to zero in 1900. For the period 1931--1968 relied on estimates from the recent reconstruction efforts by Southwest Fisheries Science Center and California Department of Fish and Game scientists [@ralston_documentation_2010]. This effort utilized newly available spatial information regarding groundfish landings back to 1931. This method is probably quite reliable for `r spp`, since it was identified as a separate market category. Landings between 1969--1977 were based on California fish tickets with a ratio estimator approach and between 1978 to 1980 were pulled from CALCOM database. Prior to 1969, gear type associated with landings were not available and were allocated between trawl and hook-and-line gear based upon the proportions starting in 1969 with no landings assumed to be based on pot gear since the landings with pot gear were negligible (e.g., less than 0.5 mt in 1969 and 1970) until 1971. California commercial landings from 1981--2024 were extracted from \gls{pacfin}. 

Oregon landings reconstructions begins in 1927 through 1986 [@karnowski_historical_2014]. -@low_sablefish_1976 provided total landings from 1915--1926. Prior to 1915 no statistics were available, so a linear extrapolation from the 10 mt estimate for 1915 to 0 mt in 1891 was applied. Oregon landings from 1987 to 2024 were extracted from \gls{pacfin}. 

Washington completed a historical landings reconstruction for this 2019 assessment of `r spp` which was used in this assessment. These landings represent the best available information. The following information sources were included in the reconstruction: 1890 to 1908 from U.S. Fish Commission bulletin, 1915--1952 from PMFC bulletin 3, appendix (page 130, using a conversion factor of 1.75 for dressed fish), 1953 to 1969 from the Washington Statistical bulletin, and 1970--1980 from Washington fish ticket database. Landings area assignments were based on Seattle market reports and Washington Statistical bulletins. Gear type was based on PMFC bulletin 3 (page 44, Table 2) and Washington Statistical bulletins. Washington landings between 1981--2024 were extracted from \gls{pacfin}.

This assessment also included data on catch of `r spp` by the Pacific hake at-sea fishery since 1978. These 2023 assessment of `r spp` included only catch estimates from 1990--2022. This assessment extends the at-sea catches to the first year of available catch data, 1978. Across most years the catch of `r spp` in the Pacific hake at-sea fishery is relatively low, particularly compared to the landings data from other groundfish sectors contained in \gls{pacfin}. However, there have been select years where the catch of `r spp` in this fishery has been higher than average. Catch was high between 1979 and 1982 ranging between 103 mt to 359 mt. In recent years, high catch in the Pacific hake at-sea fishery is likely driven by strong recruitment events with 153 mt and 117 mt of bycatch in 2017 and 2018, respectively, and 306 mt and 161 mt in 2022 and 2023. The estimates provided from the \gls{ashop} included both discarded and retained catch of `r spp` and were included in assessment in a separate trawl catch fleet. 

Foreign catches are included in gear specific fleets. The foreign catch reconstructions were based on the records in the historical annotated landings (HAL) database [@lynde_historical_1986]. The catch by foreign vessels were very large in the late 1970s, relative to domestic fleets at that time. Previous assessments included the foreign catches in the corresponding landings gear fleet which resulted additional mortality being estimated (e.g., treated as if the estimates were landings not catches that accounted for total mortality). Since @lynde_historical_1986 indicates that the values are catches that account for both estimates of landings and discarding, these catches were separated into separate catch fleets for this assessment.    

Recreational fishery landings were included in this assessment and added to the hook-and-line landings fleet in the model. Recreational landings of `r spp` were low historically with the average mortality being less than 3 mt per year between 2001-2022, but have been sharply increased in recent years. In 2023, recreational mortality coastwide peaked at 34 mt and decreased in 2024 to 29 mt. 

This assessment also included discard fleets for each gear type. The estimates for discard mortality were based on information about historical, when available, and current discarding practices by fleet. Discard mortality was estimated for the domestic historical and current landings only, using \gls{pfmc} adopted gear-specific discard mortality rates of 20 percent for fixed gear and 50 percent for trawl gear. Previous assessments of sablefish have assumed these same discard mortality rates. The discard fleet mortality was calculated for the domestic commercial landings only (e.g., historical commercial reconstructions and landings in \gls{pacfin}). 

The calculated discard mortality for each gear between 2002--2023 used \gls{wcgop} gear-specific annual discard rates and discard mortality rates multiplied by the corresponding domestic landings in \gls{pacfin}. The discard mortality prior to 2002 for hook-and-line and pot gear was calculated using the average gear-specific discard rate between 2002--2010 and discard mortality rate multiplied by the domestic year-specific landings from 1890--2001 (e.g., landings in \gls{pacfin} and the historical catch reconstructions). The discard mortality for trawl gear prior to 2002 was based upon the average of discard rates observed in the Pikitch data for 1985--1987 and discard mortality rate multiplied by the domestic year-specific landings from 1890--2001.  The discard mortality in 2024 was calculated by using the gear-specific discard rate for 2023. No discard mortality was assumed between 1942--1946 during World War II.  The estimation of the gear-specific annual discard rates is described below. 

A comparison between the total mortality from this assessment and the estimated total mortality from the previous assessment is shown in @fig-landings-comparison. 

### Discards {#discards}

Data on discards of `r spp` are available from multiple sources. A trawl discard study conducted in 1985--1987, referred to as the "Pikitch study", organized by Ellen Pikitch resulted in discard rates and length observations for various groundfish species including `r spp` [@pikitch_evaluation_1988]. The boundaries of the study was primarily within the Columbia \gls{inpfc} area, falling within Oregon/Washington waters [@pikitch_evaluation_1988; @rogers_numerical_1992]. Participation in the study was voluntary and included vessels using bottom, midwater, and shrimp trawl gears. Observers on commercial vessels collected the data, estimated the total weight of the catch by tow, and recorded the weight of species retained and discarded in the sample. Results of the Pikitch discard study were processed and provided by John Wallace (personal communication, \gls{nwfsc}, \gls{noaa}) in the form of ratios of discard weight to total weight (discard and retained) of `r spp`. 

The second source for discard data is from \gls{wcgop}. This program is part of the \gls{nwfsc} and has been recording discard observations starting in 2002. Since 2011, when the \gls{ifq} program was implemented, observer coverage rates increased to 100 percent for all the \gls{ifq} vessels in the program (i.e., through 2023) and discard rates within this sector declined compared to pre-2011 rates. Discard rates were obtained for both the \gls{ifq} (observed and electronic monitored vessels) and other sectors (e.g., open access, limited entry, etc.) for `r spp`. A single discard rate was calculated by weighting discard rates based on the commercial discards between the \gls{ifq} and other sectors and gears based on landings estimates from the \gls{gemm} report. This assessment estimated a single discard rate for each gear type using a data weighting  approach based upon the landings between sectors.  This approach to calculating discard rates is considered to be an improvement compared to approaches used in previous assessments for sablefish. The discard rates from both data sources by fleet based on gear type are shown in @tbl-discard-rates-twl -- @tbl-discard-rates-pot.  

\gls{wcgop} collects biological data for observed discards from the commercial fishery. For sablefish, only length data were available from \gls{wcgop}. However, this assessment uses an empirical weight-at-age approach to account for time-varying changes in growth requiring all composition data to be age-based  (see Section \ref{watage} for details). The observed discard length data were converted to estimated age data using a length-age key accounting for the year and area of collection (north or south of 36$^\circ$ N. latitude). The `FSA` package in `R` was used to convert lengths to ages. The package calculates probabilities of a fish being an age given length to assign an age from the length. Data from the \gls{s-wcgbt} was used to inform the estimated length-age probabilities since this data source includes annual data with spatial locations (@fig-alk). The estimated ages by gear were then expanded to the tow level and aggregated annually for each gear type. The estimated ages were then used to inform the estimation of selectivity for each of the gear-specific discard fleets.     

The aggregated discard ages by gear type are shown in @fig-data-agg-ages. Discard ages by gear and year are shown in @fig-discard-ages-trawl -- @fig-discard-ages-pot. Generally, the trawl discards younger fish compared to the other gear types, with both hook-and-line and pot gear discarding a wider range of ages compared to trawl.  

### Composition Data {#fishery-bds-data}

Data for all states were extracted from \gls{pacfin} Biological Data System. Broadly, the weighting of commercial biological samples was conducted via the following method using the `R` package \href{https://github.com/pfmc-assessments/pacfintools}{\texttt{pacfintool}} developed and managed by scientists at the \gls{nwfsc}. The package queries, filters, and expands fishery biological data based on the following steps:

\begin{enumerate} 
\item Expand the sample weight of lengths or ages from the state recorded sub-sample, consisting of one or more baskets of fish, to the estimated total landings in that market category (or trip for ungraded samples). When sample weights were unavailable, gender-specific weight-length relationships were used to approximate the weight of the sample. 
\item Sum the trip-expanded values within model-based gear fleets and state combinations. Data sampled from larger landings thus account for more weight in the sum to better reflect the total landings.
\item Expand the values to gear-specific landings, ensuring that data by state are expanded based upon the total landings within that state.
\item Calculate input sample sizes based upon the number of trips and samples.
\end{enumerate}

The input sample sizes for each fleet in the model were calculated as:

\begin{centering}

Input N = $N_{\text{trips}} + 0.138 * N_{\text{fish}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $<$ 44

Input N = $7.06 * N_{\text{trips}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $\geq$ 44

\end{centering}

Commercial length and age data were queried from \gls{pacfin}. Commercial length data are available in \gls{pacfin} starting in 1974 and age data in 1983.  This assessment incorporated only commercial age data to estimate the age distribution of removal by gear type. Initial investigation into the available age data identified a number of age samples that did not appear to be used in the 2019 assessment. Comparisons between the number of age samples by year for trawl and fixed gear (e.g., hook-and-line and pot combined based on the previous assessment) are shown in @tbl-twl-age-samples-comp -- @tbl-fixed-age-samples-comp. The majority of the omitted age data were from Oregon. Generally, there were two reasons these age data were omitted; 1) no recorded ageing method or 2) samples marked as special samples, leading these samples to be filter out from the data. The \gls{cap} was able to confirm that the method to age sablefish has not changed across time and most ages are read using break-and-burn methods. Given this, these ages with no ageing method denoted in \gls{pacfin} are likely break-and-burn reads and should be included in the assessment. In 2019, scientists at the \gls{nwfsc} initially noticed that there were a number of data records in Oregon marked as "special samples" in early years of available data. After working with data experts at \gls{odfw}, it was concluded that these samples were likely collected using standard sampling protocols and should be random samples of market category fish and should be included in assessments.  

The total number of age samples, trips samples, and the calculated input sample size by year and gear type are shown in @tbl-twl-age-samples, @tbl-hkl-age-samples, and @tbl-pot-age-samples. Across all years, 28 percent, 50 percent, and 22 percent of all age data arise from California, Oregon, and Washington, respectively. By gear, 57 percent of available age data are from the trawl fleet, 32 percent from hook-and-line, and 11 percent from pot. The trawl fleet catches younger fish compared to hook-and-line and pot (@fig-data-agg-ages). The age data from retained landing by hook-and-line and pot gear are similar with each fleet having a higher proportion of female fish compared to male fish. The age data by year from the trawl fleet are shown in @fig-data-trawl, hook-and-line in @fig-data-hkl, and pot in @fig-data-pot.

## Fishery-Independent Data

Historically, data from four research surveys have been used to assess sablefish providing fishery-independent information about the abundance, distribution, and biological characteristics of `r spp`. The longest time series of fishery-independent data arises from the \gls{s-wcgbt} survey which began in 2003. This survey samples the shelf and slope off the U.S. West Coast covering depths from 55--1,280 m (30--700 fathoms) on an annual basis (excluding 2020 due to COVID-19). This assessment also used data from two additional fishery-independent surveys: \gls{s-nslope} and the \gls{s-tri}. Data from the \gls{s-aslope} has been used in previous assessments of sablefish, but due to issues found in the age data, this survey was not included in this assessment (see Section \ref{data-not-used} for additional information). 

The indices from each fishery-independent source used with this assessment were standardized for comparison. Each index of abundance was re-scaled relative its mean index value (i.e., each index centered around 1.0) shown in @fig-index-stand.

### NWFSC West Coast Groundfish Bottom Trawl Survey {#wcgbt-data}

The \gls{s-wcgbt} is based on a random-grid design; covering the coastal waters from a depth of 55--1,280 m [@bradburn_2003_2011]. This design generally uses four industry-chartered vessels per year assigned to a roughly equal number of randomly selected grid cells and divided into two ‘passes’ of the coast. Two vessels fish from north to south during each pass between late May to early October (i.e., except for 2019 which had one vessel per pass). This design therefore incorporates both vessel-to-vessel differences in catchability, as well as variance associated with selecting a relatively small number (approximately 700) of possible cells from a very large set of possible cells spread from the U.S./Mexico to the U.S./Canada borders.

`r Spp` are observed across the full range of latitudes (@fig-positive-lat-wcgbt) and depths (@fig-positive-depth-wcgbt) sampled by the \gls{s-wcgbt}. The sex ratio of positive tows is roughly 50:50 between females and males between depths of 55--400 m, greater than 50 percent male between 400--1,100 m, and greater than 50 percent female at the deepest depths sampled (@fig-sex-ratio-wcgbt). The size and age of sablefish observed by latitude and depth are shown in @fig-wcgbt-map-density. Generally, older sablefish for both sexes are found at deeper depths compared to younger fish that are more commonly observed between 55--500 m (@fig-wcgbt-depth-len-age). The observed fraction female by age and year is shown in @fig-wcgbt-age-sex-ratio.

Geostatistical models of biomass density were fit to survey data using the R package \gls{sdmtmb} developed by @Anderson:2022:SRP. These models can account for latent spatial factors with a constant spatial Gaussian random field and spatiotemporal deviations to evolve as a random walk Guassian random field [@thorson_geostatistical_2015]. Tweedie, delta-binomial, delta-gamma, and mixture distributions were investigated. Results are only shown for the distribution that led to the best model diagnostics, e.g., similar distributions of theoretical normal quantiles and model quantiles, high precision, lack of extreme predictions that are incompatible with the life history, and low \gls{aic}. Estimates of biomass from this best model were predicted using a grid based on available survey locations. The \href{https://pfmc-assessments.github.io/indexwc/}{\texttt{indexwc}} and R package was used to conduct the analysis.

The chosen model used a delta model with a gamma distribution for the catch-rate component. A logit-link was used for encounter probability and a log-link for positive catch rates. The response variable was catch (mt) with an offset of area (km$^2$) to account for differences in effort. Fixed effects were estimated for each year.
The survey pass was included as a covariate. Vessel-year effects, which were historically used for index standardization of this survey, were not included because the estimated variance for the random effect was close to zero. Vessel-year effects were more prominent when models did not include spatial effects and instead vessel-year terms accounted for the random selection of commercial vessels used during sampling [@helser_generalized_2004; @thorson_accounting_2014]. Spatial and spatiotemporal variation were included in the encounter probability and the positive catch rate model. Spatial variation was approximated using 500 knots. The quantile-quantile (Q-Q) plot for the delta-gamma model is show in  @fig-qq-wcgbt. No spatial or spatiotemporal patterns were found in the Pearson residuals. The relative index of abundance for `r spp` decreased to the lowest levels between 2008 and 2010, begun to slowly increase between 2011 and 2019, and then sharply increased in 2021 to 2022 and remained high in 2023 and 2024 (@fig-index-wcgbt). The estimated proportion of biomass observed by the \gls{s-wcgbt} north and south of 36$^\circ$ North latitude over the last five years of the survey are shown in @tbl-prop-area.

Length and age samples are collected by the \gls{s-wcgbt}. The length data were not used in this assessment and the age data were processed into age data bins between 0 and 50 years. The marginal age compositions were expanded to the tow level and strata level (@tbl-wcgbt-strata).  Input sample size for the marginal age composition were calculated using a multiplier (e.g., 2.38) by on the number of positive tows with age samples (@tbl-wcgbt-samples) based upon research by @stewart_bootstrapping_2014. The ages aggregated over all years are shown in @fig-data-agg-ages and by year in @fig-data-wcgbt. The mean age by year with 95 percent confidence intervals based on current sample sizes is shown in @fig-data-wcgbt-mean-age. The data include observations of sablefish ranging from 0--91 years of age. The majority of unsexed fish in these data are age 0 fish where sex cannot often be reliably determined.  

### NWFSC Slope Survey {#nslope-data}

The \gls{s-nslope} covered waters throughout the summer from 183 m to 1,280 m north of 34$^\circ$ 30$^\prime$ N. latitude, which is near Point Conception, from 1999--2002. The survey sampled 80 fixed east - west transects of latitude, separated by 10 minutes of latitude. Five stations in each transect were selected from two depth categories: shallow strata (183--549 m) and deep strata (550--1,280 m). There were a total of 400 possible stations to sample from each year, with 302--327 successful tows on average per year. The survey was conducted from mid-August to mid-October in 1998 but was somewhat earlier in 1999 and 2000 (late-June to late- September).

`sdmTMB` was used to estimate a spatial and spatiotemporal index for the \gls{s-nslope}. The chosen model used a delta model with a log-normal distribution for the catch-rate component. A logit-link was used for encounter probability and a log-link for positive catch rates. The response variable was catch (mt) with an offset of area (km$^2$) to account for differences in effort. Fixed effects were estimated for each year. No other covariates were modeled. Spatial and spatiotemporal variation were included in the encounter probability and the positive catch rate model. Spatial variation was approximated using 500 knots. Q-Q plot is shown in @fig-qq-nwfslope. No spatial or spatiotemporal patterns were found in the Pearson residuals.  The estimated index shows a relatively flat trajectory over the survey period except for the increase in 2000 (@fig-index-nwslope). 

Length and age data were collected by the \gls{s-nslope}. The length data were not used in this assessment and the age data were processed into age data bins between 0 and 50 years. The marginal age compositions were expanded to the tow level and strata level (@tbl-nwslope-strata).  Input sample size for the marginal age composition were calculated using a multiplier (e.g., 2.38) by on the number of positive tows with age samples (@tbl-nwslope-samples) based upon research by @stewart_bootstrapping_2014. The ages aggregated over all years are shown in @fig-data-agg-ages and by year in @fig-data-nwfsc-slope. The mean age by year with 95 percent confidence intervals based on current sample sizes is shown in @fig-data-nwfsc-slope-mean-age. The data include observations of sablefish ranging from 0--73 years of age. 

### AFSC/NWFSC West Coast Triennial Shelf Survey {#tri-data}

The \gls{s-tri} was first conducted by the \gls{afsc} in 1977, and the survey continued until 2004 [@weinberg_estimation_2002]. Its basic design was a series of equally-spaced east-to-west transects across the continental shelf from which searches for tows in a specific depth range were initiated. The survey design changed slightly over time. In general, all of the surveys were conducted in the mid-summer through early fall. The 1977 survey was conducted from early July through late September. The surveys from 1980 through 1989 were conducted from mid-July to late September. The 1992 survey was conducted from mid-July through early October. The 1995 survey was conducted from early June through late August. The 1998 survey was conducted from early June through early August. Finally, the 2001 and 2004 surveys were conducted from May to July.

Haul depths ranged from 91--457 m during the 1977 survey with no hauls shallower than 91 m. Due to haul performance issues and truncated sampling with respect to depth, the data from 1977 were omitted from this analysis, as is general treatment in groundfish assessments. The surveys in 1980, 1983, and 1986 covered the U.S. west coast south to 36.8$^\circ$ N. latitude and a depth range of 55--366 m. The surveys in 1989 and 1992 covered the same depth range but extended the southern range to 34$^\circ$ 50$^\prime$ N. latitude (near Point Conception). From 1995 through 2004, the surveys covered the depth range 55--500 m and surveyed south to 34$^\circ$ 50$^\prime$ N. latitude. In 2004, the final year of the \gls{s-tri} series, the \gls{nwfsc} \gls{fram} division conducted the survey following similar protocols to earlier years. Due to changes in survey timing, the \gls{s-tri} data have been split into independent early (1980 - 1992) and late (1995 - 2004) survey time series. The previous assessment for sablefish the split of the time series was done via a shift in catchability (Q) between the 1992 and 1995 survey years. However, this assessment opted to split the early (1980--1992) and late (1995--2004) period from this survey into two separate fleets which better supported differences in selectivity and data weighting.

`sdmTMB` was used to estimate indices of abundance for both the early and late period for the \gls{s-tri}. The estimated index shows a relatively flat trajectory over the period from 1980--1989 with an increase in 1992 (@fig-index-tri-early). The late period of the \gls{s-tri} had a flat trend between 1995 and 1998, then an increase in 2001 and 2004 (@fig-index-tri-late). Q-Q plots for each survey period suggested that the gamma distribution (@fig-qq-tri-early and @fig-qq-tri-late) fit the data, better than a log-normal distribution (results not shown). No spatial or spatiotemporal patterns were found in the Pearson residuals. 

Length and age data were collected by the \gls{s-tri}. The length data were not used in this assessment and the age data were processed into age data bins between 0 and 50 years. The marginal age compositions were expanded to the tow level and strata level for each survey period based upon the change in sampling depth and latitude (@tbl-tri-early-strata and @tbl-tri-late-strata).  Input sample size for the marginal age composition were calculated using a multiplier (e.g., 2.38) by on the number of positive tows with age samples (@tbl-tri-early-samples and @tbl-tri-late-samples) based upon research by @stewart_bootstrapping_2014. During the early \gls{s-tri} number of tows where age data were available was limited compared to the number of positive tows. The age data from 1986 were not used in the base model since they represented only one tow out of the 372 positive tows that year.  In the late period of the \gls{s-tri} the number of tows with age data increased relative to the early years, but were still limited compared to the total positive tows by year except in 2004.  The age data from 1998 and 2001 were not included in the base model because they did not appear to be a representative sample of the length data (@fig-data-tri-len-age). The location of age data by year compared to the location of tows with lengths sampled are shown in @fig-data-tri-tows.

The ages aggregated over all years are shown in @fig-data-agg-ages and by year for the early years @fig-data-tri-early and late year @fig-data-tri-late. The mean age by year with 95 percent confidence intervals based on current sample sizes is shown in @fig-data-tri-early-mean-age and @fig-data-tri-late-mean-age. The during the early period of the \gls{s-tri} a range of ages from 0 to 21 were observed, with the majority of ages observed were from 1 to 4. The during the late period of the \gls{s-tri} a range of ages from 0 to 36 were observed, with the majority of ages observed were from 1 to 6. 

## Additional Data Considered {#data-not-used}

### AFSC Slope Survey

The \gls{s-aslope} operated during the months of October to November aboard the R/V Miller Freeman. Partial survey coverage of the U.S. West Coast occurred during the years 1988 - 1996 and complete coverage (north of 34$^\circ$ 30$^\prime$ N. latitude) during the years 1997 and 1999--2001. Typically, only these four years that are seen as complete surveys are included in groundfish stock assessments.

The number of tows, positive tows, tows with age data sampled, and total number of ages are shown in @tbl-afslope-samples.  The \gls{s-aslope} had an unusually high rate of positive tows for sablefish (e.g., ~ 98 percent of tows observed sablefish), particularly compared to the \gls{s-nslope} (~ 86 percent) that was conducted across similar years and depths. This high rate of positive tows created prevented the use of the traditional delta-model given that nearly all tows were positive for sablefish. A tweedie distribution was used to estimate an index of abundance shown in @fig-data-afslope-index.

During investigations of the age data from the \gls{s-aslope}, it was determined that aged fish for sablefish did not appear to be a representative sample of the lengths observed (e.g., fish identified for otolith collection were not selected randomly from all fish caught, @fig-data-afslope-len-age). This same issue was also identified for this survey in the most recent assessment of Dover sole.  Given the concerns about the data collected by the \gls{s-aslope} for sablefish, and the fact that there was a comparable survey data set during these years, it was decided to not include data from this survey in the base model.

### Fournier Transform Near Infrared Spectroscopy Age Data

Scientists at the \gls{nwfsc} and at the \gls{cap} laboratory have been working on developing age estimates using \gls{ftnirs} combined with Neural Net (NN) models.  The approach takes a spectral scan of an otolith, the spectral scan information is then passed through a NN model with varying covariates to predict an age. To date, a total of 11,722 otoliths collected by the \gls{s-wcgbt} from 2015--2024 have been scanned using \gls{ftnirs} with a predicted age NN model age accounting for otolith structure weight, fish weight, depth, latitude, sex, and month in the NN model. All of these predicted ages have a corresponding traditional age that is included in this assessment. Otoliths collected from the commercial fishery collected from 2018--2024 were also scanned, with not of these otoliths having an existing age from traditional ageing methods. The NN model was trained on age data from the \gls{s-wcgbt} from 2017--2022 and then the trained model was used to predict ages from 2015--2016 and 2023--2024.  The trained NN model was able to predict ages from the \gls{s-wcgbt} in 2015--2016 that appeared to align with the traditional ages. However, when that same model was used to predict ages from otoliths collected in 2023--2024 there appeared to be departures between the predicted ages compared to the traditional ages.     

The work on \gls{ftnirs} is ongoing \gls{nwfsc} and best practices are still evolving, and given the ongoing nature of this work and the challenges identified in predicting ages from 2023--2024 these data were not used in this assessment. Future assessments for sablefish should evaluate NN predicted ages for sablefish. 

### Enhanced Data Collection Program (EDCP) Discard Rates

The Enhanced Data Collection Project (EDCP) conducted off Oregon for trawl vessels in 1997 collected discarding data from select vessels that estimated a discarding rate of 0.40. However, the discarding estimates from this study were found to not be representative of the fleet at large. The EDCP data were not included in this assessment due to concerns about representativeness. 

## Biological Data

### Natural Mortality {#m}

The current method for developing a prior on natural mortality ($M$) for West Coast groundfish stock assessments is based on Hamel and Cope [-@hamel_development_2022], a method for combining meta-analytic approaches relating the $M$ rate to other life-history parameters such as longevity, size, growth rate, and reproductive effort to provide a prior on $M$. This approach modifies work done by Then et al. [-@then_evaluating_2015] who estimated $M$ and related life history parameters across a large number of fish species from which to develop an $M$ estimator for fish species in general. They concluded by recommending $M$ estimates be based on maximum age alone, based on an updated Hoenig non-linear least squares estimator $M = 4.899A^{-0.916}_{\text{max}}$. Hamel and Cope [-@hamel_development_2022] re-evaluated the data used by Then et al. [-@then_evaluating_2015] by fitting the one-parameter $A_{\text{max}}$ model under a log-log transformation (such that the slope is forced to be -1 in the transformed space [@hamel_development_2022], the point estimate and median of the prior for $M$ is:

\begin{centering}

$M=\frac{5.4}{A_{\text{max}}}$

\end{centering}

\vspace{0.5cm}

where $A_{\text{max}}$ is the maximum age. The prior is defined as a log-normal distribution with mean $ln(5.4/A_{\text{max}})$ and standard error = 0.31.  

The maximum age for `r spp` was selected based on available age data from all West Coast data sources. The oldest aged `r spp` was 102 years, captured by the commercial fishery in 2006, not accounting for potential ageing error. Examining all aged fish, a maximum age of 75 was selected. Across all data sources there were limited observation greater than 75 years of age. There are a higher frequency of older males compared to females observed in the data, however, females grow to larger sizes and generally have higher fishery selectivity which may bias the sex-ratio of older individuals. Using a maximum age of 75, the median of the prior was 0.72 yr$^{-1}$ with a standard error of 0.31.

### Sex Ratio {#sex-ratio}

The sex ratio observed by depth showed some patterns by sex with roughly a 50:50 ratio between sexes from 55--400 m, slightly more males than males from 500--1,100 m, and more females at the greatest depths (@fig-sex-ratio-wcgbt). The sex ratio (e.g., fraction female) varied by age in the \gls{s-wcgbt} data with a 50:50 ratio at younger ages and then a higher ratio of males from approximately age 10 and older (@fig-wcgbt-age-sex-ratio). The reduction in the number of females compared to males for these ages could either be due to a higher fishing pressure of female fish since they are generally larger-at-age compared to males and or due to differences in natural mortality by sex.  This assessment assumed the same natural mortality between the sexes in the base model but did explorations to allowing for sex-specific estimates.

### Growth {#growth}

Range-wide investigations of `r spp` growth suggest that growth varies across the northeastern Pacific, with a generally increasing cline in length-at-age with latitude [@mcdevitt1987sablefish, @echave2012fishbullinterdecadal, @gertseva2017icesjmsspatial, @kapur_oceanographic_2020]. Break points in growth have been identified at around $50^\circ$ N. latitude (approximately the northern end of Vancouver Island, Canada), where north of this breakpoint female asymptotic-length estimates were consistently over 70 cm and south of this breakpoint female asymptotic-length estimates were below 66 cm [@kapur_oceanographic_2020]. A second break point was identified by [-@kapur_oceanographic_2020] at 36$^\circ$ N. latitude (approximately Monterey, California), where asymptotic size for females and males to the south were 60 cm and 55 cm, respectively. 

Female `r spp` generally reach larger sizes compared to males. The size at age for the oldest `r spp` is quite variable leading to uncertainty in the estimated maximum size for both females and males.  For example, the  female `r spp` the 95 percent quantile of all observed lengths coastwide from the \gls{s-wcgbt} is from 55--77 cm for females and 51--67 cm for males. As found by @kapur_oceanographic_2020 splitting data from the \gls{s-wcgbt} north and south of 36$^\circ$ N. latitude results in smaller growth-at-age in the south compared to the north (@fig-external-growth).  Examining the von Bertanlaffy growth parameters by latitude also shows that parameters vary in the south compared to the north, but potentially indicate a slightly more northern change point, around 38$\^circ$ N. latitude, in growth (@fig-external-growth-lat).

The review of the 2019 assessment noted that a non-time-varying growth curve resulted in periods of misfit to conditional-age-at-length data from the \gls{s-wcgbt} indicating that growth may be varying by year and age. The review panel recommended that future assessments explore an empirical weight-at-age approach which could account for time-varying growth. In order to better account for variation in growth, this assessment uses an empirical weight-at-age approach in the base model. 

### Weight-at-Age {#watage}

A matrix of empirically derived population weight-at-age data by year is used in the current assessment model to translate numbers-at-age to biomass-at-age. Annual weight-at-age data was modeled from biological samples from the \gls{s-wcgbt} between 2003--2024. Weight-at-age from fishery samples were not included because weight is not reported for samples in California and available for very limited samples in Washington.  The samples by year, sex, and age are shown in @tbl-watage-samples with the totals in the age 25 column reflecting the total for fish age 25 and older.

A generalized linear mixed model (GLMM) with a log-normal distribution has been used to model weight-at-age data by sex and area (e.g., north and south of 36$^\circ$ N. latitude), with weight relating to a smoothed effect of age between ages zero and 30; random effects for cohort and year; and fixed effects for sex. The model was modified from the model used for Pacific hake Weights from fish ages 30 and above for each year were pooled, and thus, ages 30- 70 are assumed to have the same weight-at-age. Estimated parameters from this model, weighted by collection area, were used to predict sex-specific coastwide weight-at-age for ages zero to 30 from 2003--2019 and 2021--2024. The means of annual, sex and age-specific estimates were used for input into the assessment model (@fig-data-watage, @fig-weight-at-age-female, and @fig-weight-at-age-male). 

The biomass at the start of a given year is based on the weight-at-age from the same mid-year, when samples are collected by the \gls{s-wcgbt}. A similar approach is used by the Pacific hake assessment, since samples at the beginning of the year are limited.  Prior to 2003, weight-at-age input to Stock Synthesis is assumed to be equal to the mean of all available years for each respective age (2003--2019 and 2021--2024). The weight-at-age for 2020 was assumed to be equal to the mean of 2019 and 2021 by sex for each respective age. Projected weight-at-age data are based on age-specific means from the most recent five years (2020 -– 2024).

The use of empirical weight-at-age data is a convenient method to capture the variability in both the weight-at-length relationship within and among years as well as the variability in length-at-age data, without requiring parametric models to represent growth relationships. The review of the 2019 assessment of sablefish noted that there appeared to be time-varying growth and that future assessments should explore a weight-at-age approach to more accurately reflect patterns in growth variability.   


### Maturity and Fecundity {#mat-fecund}

New maturity reads and analysis were available for this assessment. A total of `r dim(maturity_data)[1]` sablefish maturity samples were collected by the \gls{s-wcgbt} in 2010, 2015, 2018, 2021, and 2022 (@tbl-maturity-samples). The maturity samples were evaluated for functional maturity that classifies maturity with developing oocytes as mature or immature. The maturity-at-age or -length estimates were evaluated north and south of 36$^\circ$ N. latitude. Of the samples processed, sablefish were identified to be mature as early as age `r min(maturity_data[which(maturity_data$Area == "North" & maturity_data$functional_maturity == 1), "age"])` and `r min(maturity_data[which(maturity_data$Area == "South" & maturity_data$functional_maturity == 1), "age"])` in the north and south, respectively.  Generally, across samples, sablefish matured at younger ages more frequently in the north compared to the south (@fig-maturity-data). 

Maturity was estimated using a spatial models using age or length as a predictor.  A total of 10 spatial and spatiotemporal models were considered, but because of the sparsity of data only models with spatial effects of spatially varying coefficients (e.g., no fixed year effects of spatiotemporal fields) were considered. There was little support for including a day of year effect, so that was omitted from the models and results. A spatial field and spatially varying effect of length (spatial_varying ~ length_scaled or spatial_varying ~ age_scaled ) were also included which are analogous to an spatial intercept and spatial slope, respectively; these components allow maturation rates to vary spatially but are assumed relatively constant through time. 

Maturity as a function of age shows a strong spatial gradient, with lower age-at-50-percent ($a_{50}$) estimates in the north compared to the south. Maturity as a function of length shows a weaker spatial gradient, with more patchiness (e.g., several estimates of above average length-at-50-percent ($l_{50}$) in southern California). For each of the models, estimates of $a_{50}$ and $a_{50}$ were generated in two ways: coastwide and spatial split north and south of 36$^\circ$ N. latitude. A coastwide maturity curve was estimated by weighting the spatial split curves using a biomass weighted prediction grid from the \gls{s-wcgbt}. The assessment uses the biomass weighted maturity curve (spatial, @fig-maturity-ogive).

Available data suggests that `r spp` are determinate spawners (i.e., total oocytes at the beginning of the spawning season is equivalent to total annual spawning output) and spawn three to four times per year [@hunter1989; @macewicz1994]. The total number of oocytes at the beginning of the spawning season appears to be linearly proportional to weight [@hunter1989], implying that spawning output for a mature female is also proportional to weight. This assumption has been used in previous `r spp` stock assessments and is retained here in the absence of new information. Data on skipped spawning are unavailable, as are data on environmental effects or other factors that could cause fecundity to vary non-linearly with weight.

The product of the maturity-at-age and the fecundity-at-age (e.g., equal to weight) is show in @fig-fecundity-maturity.

### Ageing Precision and Bias

Observed `r spp` ages are derived from visually counting rings on otoliths using 'break-and-burn' methods. These counts can be large because `r spp` are long-lived and the repeatability of individual age estimates is imperfect, especially for older fish. Age-reading staff have indicated that `r spp` can be difficult to age. The observed age can differ, sometimes substantially, from the true age of a fish (i.e., "reading error"). Ageing error can be decomposed into the difference between true age and average-read age (bias) and variability around that average read age (precision).  

The large majority of aged `r spp` used in the assessment were aged by the \gls{cap}.  Within-lab ageing error was estimated for \gls{cap}. Break-and-burn double reads of more than 12,000 otoliths were provided by the \gls{cap} lab (unpublished data).  An ageing error estimate was made based on these double reads using a computational tool specifically developed for estimating ageing error [@punt_quantifying_2008] and using release 2.1.0. of the R package \href{https://pfmc-assessments.github.io/AgeingError/index.html}{AgeingError} for input and output diagnostics. 

Ageing error analyses were run exploring ageing bias and linear or curve-linear error with age. One reader was selected as unbiased reader 1 and other read ages from various other readers where grouped into a reader 2 vector. A comparison of age reads are shown in @fig-age-reader. The linear model with no bias in age was selected as the final model (@fig-ageing-error).  


## Environmental/Ecosystem Indicator Data {#rec-index-data}

Linear models were used to examine relationships between recruitment deviations in log-space from the 2023 assessment of sablefish and predictors from the GLOYRS model output. The period from 1993--2019 as training data, leaving 2020--2024 as out-of-sample for use in base model. All combinations of the GLORYS predictors were fit, excluding correlated variables from the same model, and limiting the the total number of predictors in any model to three (just over 8 data points per predictor). Model selection was carried out using the `dredge` function in the `MuMIn` package in `R` [@R-base; @MuMIn-cite]. Candidate models were evaluated based on their $\Delta$AICc and number of predictors.

Five models had $\Delta$AICc values $\le$ 2.0 (@tbl-rec-index-aic). All models included cross-shelf transport during pelagic juvenile (CSTpjuv), and benthic juvenile (CSTbjuv) stages. Model 3 was chosen as the best-fit because it had the fewest predictors (2), and these two predictors were in all top-five models providing consistency. The best-fit model explained 37 percent of the variation in recruitment deviations from 1993--2022 (r^2^ = 0.37, @tbl-rec-index-aic, @fig-glorys-fit). The model tracked the data well with most recruitment deviations falling with $\pm$ 1.0 standard error of the recruitment index (@fig-glorys-fit).

The remaining four models included either Tspawn, DDpre, CSTegg, or CSTyolk as predictors. These results suggest that different additional terms might help explain variance in different years, but that CSTpjuv and CSTbjuv provide a consistent basis for prediction. Including an additional factor like Tpre would increase the explained variance by \~ 10 percent points (r^2^ = 0.47).

For all models recruitment was negatively correlated with CSTpjuv suggesting that processes like upwelling may be important for producing feeding conditions conducive to survival. CSTbjuv was positively correlated with recruitment, which may indicate that onshore transport during the shift to benthic habitat leads to better recruitment. Both the ROMS analysis and the results here suggest that colder water during the female preconditioning stage (negative correlation with DDpre, here model 2) results in higher recruitment (@fig-glorys-terms).

The projected recruitment index points are shown in @fig-glorys-pred and with uncertainty in @fig-rec-index. See Section \ref{rec-appendix} for additional details.
