# Assessment

## History of Modeling Approaches

The first `r spp` stock assessment was completed in 1984 [@francis_status_1984], followed by frequent assessments since then [@francis1985sablefish; @mcdevitt1987sablefish; @methot1988sablefish; @methot1989sablefish; @methot1990sablefish; @methot1992; @methot1994; @crone1997sablefish; @methot1998sablefish; @schirripa2001sablefish; @schirripa2002sablefish; @schirripa2005sablefish; @schirripa2007sablefish; @stewart2011sablefish; @johnson2016sablefish; @haltuch_status_2019; @kapur_status_2021; @johnson_status_2023]. Previous assessments have largely drawn similar conclusions regarding historical trends, with assessments estimating a rapid decline in the population size and status in the 1970s and 1980s due to high fishing pressure. Previous assessments have estimated a wide range of unfished spawning output levels between 100,000 mt up to approximately 250,000 mt, indicating a high level of uncertainty regarding the absolute scale of the `r spp` population off the West Coast.

The 1984 assessment examined catch-per-unit-effort (CPUE) data from the 1979 to 1983 \gls{nmfs} pot survey [@francis_status_1984]. Subsequent stock assessments were age-structured of varying complexity. The 1985 age-structured assessment utilized a simulation model to examine maximum sustainable yield ($MSY$) by incorporating estimates of $M$, average weight-at-age, recruitment, and relative age-specific catchability. The model relied on \gls{nmfs} trawl and pot surveys as well as parameter estimates generated from independent research. The 1987 `r spp` assessment extended the NMFS survey time-series and primarily consisted of a modified yield-per-recruitment analysis focusing on the minimum size limit (22 inches) implemented in 1983.

In 1988, a catch-at-age analysis using an early version of the Stock Synthesis modeling framework, which is the basis for all subsequent assessments, was implemented [@methot1988sablefish]. This model included two fleets, fixed gear and trawl, and two years of fishery biological data. NMFS trawl and pot surveys provided indices of abundance, and estimates of exploitation rate were based on tag-recapture information generated from a tagging study that began in 1971. The 1989 `r spp` stock assessment followed a similar approach, though revisions in the age-determination criteria for `r spp` caused an increase in the observed proportion of old fish and a decrease in the estimate of $M$ from 0.15 to 0.09 yr$^{-1}$. The 1990 assessment [@methot1990sablefish] explicitly modeled stock structure with a northern population (U.S. Vancouver and Columbia INPFC areas) and a southern population (Eureka, Monterey, and Conception INPFC areas). Including spatial structure was motivated by differences in growth rates and the hypothesis of low migration rates. The spatial models facilitated comparisons between and among areas with signals in the raw data.

In 1992, the assessment reverted to a single stock area, excluding the Conception INPFC area [@methot1992]. Data from the \gls{s-tri} were used to extrapolate survey estimates to the entire assessment area (Monterey through U.S. Vancouver INPFC areas). Analysis focused on exploring the trade-off in fitting the trawl-survey biomass and the trend from the pot survey. The depth stratified age- and length-composition data suggested that movement of `r spp` into deep water was more closely related to their age than size. The 1994 assessment [@methot1994] was similar to the 1992 analysis, but the survey was used as an absolute measure of biomass after extrapolation to the coast-wide level. The 1997 assessment [@crone1997sablefish] added CPUE data and noted difficulties fitting all indices well. The 1998 assessment [@methot1998sablefish] focused on the inclusion and exclusion of the pot survey index and the use of commercial logbook CPUE.

The 2001 assessment [@schirripa2001sablefish] focused on evaluating the sensitivity of the results to the treatment of the survey data and trade-offs among pot survey and logbook indices of abundance. This assessment was the first to introduce the possibility that `r spp` recruitment may be linked to environmental factors. The 2002 assessment [@schirripa2002sablefish] was an update to @schirripa2001sablefish and focused mainly on newly available data from existing sources. It was the first assessment to detect the strong 1999 and 2000 cohorts in the 2001 data, following many years of below average recruitment. A significant relationship between recruitment and sea level was identified.

Several important changes were made to the assessment of sablefish in 2005 [@schirripa2005sablefish]. Landings and the modeled time-period were extended back to the year 1900. Separate selectivity curves were implemented for the trawl surveys, and years with limited geographic coverage in the \gls{s-tri} were eliminated. Discard data from the relatively new observer program were included and discard mortality was investigated. Sea level was used as an explicit offset in the population dynamics to expected recruitment.

The 2007 assessment [@schirripa2007sablefish] included newly available data and changed the treatment of the sea level index of recruitment within the stock assessment model to be a survey index of recruitment with observation error, rather than an explicit offset in the population dynamics to expected recruitment. The assessment made the explicit assumption that catchability for the \gls{s-wcgbt} was equal to 0.56, which was modeled by using only the shelf region. Uncertainty was investigated and reported primarily through alternate values for catchability.

The 2011 stock assessment [@stewart2011sablefish] reduced the number of parameters used to model fishery dynamics. Historical management actions were condensed to those that had a strong influence on fishery behavior (e.g., sorting and retention, selectivity, or both). Previously fixed leading parameters, $M$ and trawl survey catchability, were estimated or used analytical solutions. Changes led to increased, more realistic, estimates of uncertainty around stock size estimates. Repeated testing of the correlation between sea level and recruitment continued to find a significant relationship that explained approximately 35 percent of the variability in recruitment deviations. The sea-level data was used from 1970 forward, a period with length- and age-composition data, and was not retained in the base model because the index provided a recruitment signal largely consistent with that provided by the composition data. Finally, the large number of deviations about annual growth and annual selectivity curves estimated in the 2007 model were reduced, with the net effect that uncertainty was increased. The sensitivity of model results to $M$, equilibrium recruitment, and steepness ($h$), which was estimated prior to 2011, was investigated via likelihood profiles. The 2011 assessment estimated the stock to be within the management precautionary zone (e.g., above 25 percent and below 40 percent) at 34 percent. The 2015 stock assessment [@johnson2016sablefish] was an update to the 2011 stock assessment, maintaining the same model structure and focused on adding the new data and updating data weights used in the model, resulting in an estimated stock status of 35 percent.

In 2019, a new benchmark stock assessment for sablefish was conducted that evaluated the model structure used in previous assessments and incorporated a new environmental index to inform estimates of recruitment [@haltuch_status_2019]. The 2019 assessment continued to model discarding and retention similar to previous assessments, but simplified the fleet structure to two commercial fleets: trawl and a fixed gear fleet that combined pot and hook-and-line gears.  Selectivity continued to be parameterized as age-based, but the 2019 assessment opted to model selectivity for all fleets using a double-normal parameterization, moving away from using spline-based parameterization used in the previous assessment for the fishery fleets. Dome-shaped selectivity was used for all fishery and survey fleets, similar to the 2011 assessment. The assessment estimated the stock status to be just below the management target (e.g., 40 percent) at 39 percent. In 2021 and 2023, update assessments were conducted that focused on adding new data while retaining the 2019 model structure [@kapur_status_2021; @johnson_status_2023]. The 2021 update assessment updated all data and estimated a stock status of 58 percent  [@kapur_status_2021]. Finally, the 2023 update assessment was considered a "limited" update where only recent catches and new \gls{s-wcgbt} survey data were added. The 2023 limited update assessment estimated very strong recent recruitments at the end of the times (e.g., 2020 and 2021), driving the stock up with an estimated stock status of 63 percent.


## Most Recent Stock Assessment Review Panel Recommendations

The \gls{star} Panel [report](https://www.pcouncil.org/documents/2019/10/sablefish-star-panel-report-july-8-12-2019.pdf/) from the 2019 benchmark assessment made the following suggestions:

*Short Term*

**Recommendation**: To understand whether regional differences in growth, and associated size or age composition,
are behind the strong tensions observed in age and length composition data, future assessment models should evaluate having separate fixed gear fleets north and south of 36$^\circ$ N (as discussed in unresolved problems and major uncertainties). The potential merits of other regional differences in fleet structure could also be explored. 

**Response**: The \gls{stat} explored using regional based fleets, however, there are limited age data available south of 36$^\circ$ N. latitude which prevented further exploration of this approach. The \gls{stat} attempted to account for time-varying and regional differences in growth by using an empirical weight-at-age approach, where annual coastwide weight-at-age data was a biomass weighted average of weight-at-age north and south of 36$^\circ$ N. latitude.


**Recommendation**: Future assessments should consider the use of empirical weights-at-age. One approach would be to begin with the WCGBT data and use it to fit (outside model) a smoother outside the model (see Jim Ianelli for code that uses a random effects model to estimate weights using empirical
data by cohort and year). This would avoids confounding weight at age with growth estimates (e.g., Lee et al. 2019, Whitten et al. 2013), should allow the model to run faster, and should enable the model to better accommodate variability in growth (in both age and over time). Another advantage is that somatic body masses are based on actual measurements instead of model estimates which predicts mean length and then converts length to mass via a fixed set of length-weight parameters

**Response**: The \gls{stat} agreed with this recommendation and is now using an empirical weight-at-age approach in this assessment.

**Recommendation**: Consider (and potentially adopt) length based selectivity for the WCGBTS, as selectivity bias could lead to observed age zero fish not being a good representation of mean length at age 0 (which could affect estimates of growth). [Figure 13](https://www.pcouncil.org/documents/2019/10/sablefish-star-panel-report-july-8-12-2019.pdf/#page = 28) shows some summary results of this issue, including the lack of apparent growth of age 0 sablefish during the period of the survey. A related issue is that specifying the size at age 0.5 (or 1.5), as well as the CV, should be in common by sex. Dimorphic growth presumably occurs at older ages. Future assessments should consider configuring “offsets” for sex differences in the growth. The rationale for this change is that differences between sexes at such young ages seem unlikely and re-configuring the model in this way will reduce the number of parameters needed.

**Response**: This assessment retained age-based selectivity for the \gls{s-wcgbt} in order to incorporate an empirical weight-at-age approach.  The weight-at-age was informed using data from the \gls{s-wcgbt} and should better capture the variation in size-at-age across time.

**Recommendation**: Examine age-specific selectivity that is fixed at a “plus group” age (or have a reasonable
rationale as to why selectivity might be changing over those ages).

**Response**: The selectivities for all fleets in the model estimated a fixed selectivity for older ages.

**Recommendation**: Provide estimates of retention external to the model and evaluate if the approach of doing it
within the model (and then fixing the values because of discard length composition data affecting
model results other than the shape of the retention curve).

**Response**: This assessment moved to a discard fleet approach because there were concerns about model stability with retention being estimated within the model. The discard totals were estimated external to the model and the selectivity for the discard fleets were estimated using estimated discard ages.

**Recommendation**: Reconsider spline or some other non-parametric selectivity forms, as there are unexpected
behaviors observed in estimating double normal selectivities for the fixed gear fishery. The
requirement (apparently) to have to fix the “P6” parameter related to old sablefish selectivity and
some other interactions seems unusual, and several of the convergence issues were related to
selectivity parameters for some gear types/surveys. The 2015 model used a different form for
selectivity and the document provided little justification to choose one over the other. “Fewer
parameters” is a poor reason if performance overall is so much worse. The convergence
problems did seem to be largely resolved after the \gls{stat} fixed the CV of young ages.

**Response**:  The \gls{stat} explored splines for fishery and survey fleets in the model, but were not found to improve the fits to the data compared to double-normal selectivity given other fleet structure refinements.  

**Recommendation**: The CAAL plots suggest that in the early years of the WCGBTS the residuals of the biggest fish
were generally “young” and in the more recent years the pattern of observed and predicted were more consistent. This could be due to changes in growth and/or size (or age) based selectivity/availability changes and should be investigated. 

**Response**: The \gls{stat} agrees that there appeared to be periods where the conditional-age-at-length residuals were generally positive or negative.  The empirical weight-at-age approach explicitly accounts for potential time-varying growth by year.

**Recommendation**: Developing diagnostics that better evaluate sex ratio observations against model predictions
would be useful, especially given some of the differences observed in the fisheries selectivities
estimates and in sex specific natural mortality configurations compared to combined sexes
natural mortality.

**Response**: The `r4ss` package now includes improved sex ratio figures. Additionally, the sex ratio of observed ages for all fishing and survey fleets were evaluated to determine whether sex-specific selectivity was occurring. The hook-and-line and pot gear have greater selectivity for females compared to males which could lead to changes in sex ratios of selected fish over time.  The \gls{stat} did not find clear evidence for differing natural mortality rates by sex, and thus a single natural mortality was used for both sexes.  

**Recommendation**: Reducing the number of ages should be considered, as the plus group information and dynamics
beyond some ages are unlikely to change (as shown in [Figure 14]((https://www.pcouncil.org/documents/2019/10/sablefish-star-panel-report-july-8-12-2019.pdf/#page = 29))).

**Response**: The \gls{stat} agrees that the data plus group of age-50 may be larger than necessary. A sensitivity was conducted that truncated the data plus group at age 35 that shows very minor changes in the estimated stock scale but similar estimates of stock status. 

**Recommendation**: Continuing to evaluate the use of sea level and/or other environmental indicators as drivers of
both historic and future recruitments is strongly encouraged, and future assessments should strive
to clearly convey how such data explicitly relate to recruitment as well as to convey the logic and
presumed mechanisms behind the relationship.

**Response**:  The assessment opted to use a recruitment index that covered the last five years of the model given that there are significant survey and fishery data to inform recruitment estimation for earlier years.  Additionally, preliminary research conducted by Dr. Kiva Oken \gls{nwfsc} determined that including longer time series of recruitment indices may bias estimates of stock size and recommended that recruitment indices be isolated to periods where there is little to no information about recruitment from other data sources in the model.

*Medium and Long Term*

**Recommendation**: The panel had concerns about the large amount of data and the challenges faced doing things
such as estimating natural mortality and the CVs on growth and other factors. However, the core
growth parameters were generally stable, and convergence problems are not atypical when
natural mortality is difficult to estimate and selectivity patterns are all dome-shaped. The panel
notes that it is worth reflecting on whether a somewhat different modeling approach would work
better (in the longer term). The nature of the issues in the data may be stretching the capacity of
the analytical framework and software to do what needs to be done.

**Response**: The \gls{stat} agrees that estimating growth, natural mortality, selectivity, and retention with this assessment can (and did) lead to an unstable model (e.g., variable or uninformed estimates across sensitivities, and/or an inability to invert the hessian). To address these issues, this assessment made significant efforts to simplify the model structure and to improve paramaterization of key processes.

**Recommendation**: The \gls{stat} provided very helpful updates on ongoing efforts to evaluate life history
characteristics, movement patterns and management approaches throughout the range of
sablefish in the Northeast Pacific. The STAR Panel agrees with the \gls{stat} that ongoing and
future work, such as efforts to develop a trans-boundary stock assessment and management
framework, be pursued. This is based on strong indications that current stock boundaries are
likely to be inappropriate, and that a trans-boundary assessment would likely improve the ability
to estimate the scale of the population.

**Response**: This \gls{stat} agrees that work should continue to evaluate coherence of sablefish across the Northeast Pacific, including net changes in biomass due to emigration and immigration across assessment boundaries. Recent research by @kapur_tag_2025 presents estimates of trans-boundary exchange for Northeast Pacific `r spp`, which forms the basis for a sensitivity evaluation in this assessment. 

**Recommendation**: As the WCGBTS is highly informative in the model, maintaining full coastwide survey effort is
essential. However, currently the survey does not include a large fraction of the habitat south of
36$^\circ$ N, the cowcod conservation areas. Despite a lack of data in this large area, catch is allocated north and south of 36$^\circ$ N based on the estimated fraction of sablefish in these areas, and this fraction, in turn, is based on an extrapolation of survey catch rates outside the CCAs to those
inside. As fish within the CCAs are only subject to fishing pressure if and when they move, and
movement rates are variable, this concentration of effort outside of the CCAs could potentially
lead to localized depletion, which in turn could bias the signal in fishery (and potentially survey)
age and length composition from the fished areas. It would be beneficial to have survey data
from within the CCAs to inform the survey, and to allow for some evaluation of whether and
how population structure may vary inside and outside of the CCAs. There could be some
potential for local depletion elsewhere as well, given the concentration of trawl effort off of
Oregon and Washington and the decline in fishing effort and catches of both trawl and fished
gear in California north of 36$^\circ$ N.

**Response**:  The \gls{stat} attempted to evaluate the proportion of trawlable habitat south of 34$^\circ$ 47$^\prime$ N. latitude but did not have time to complete this analysis. The \gls{stat} notes that a spatiotemporal model is currently used to estimated the index of abundance for the \gls{s-wcgbt}, which can incorporate spatial and temporal information to smooth estimates across sampled and unsampled areas. However, composition data are limited in some areas, and if consistent differences exist in sablefish abundance, size, or age in unsampled compared to sampled areas, then even spatiotemporal models will not be able to accurately account for spatial heterogeneity in the biological data. Starting in 2024,the WCGBTS is now sampling within the CCA which may provide additional information to understand potential difference in sablefish abundance, size, or age inside and outside the CCA.

**Recommendation**: For the WCGBTS, evaluate cohort total mortality ($Z$) for consistency and as a check with model
values. Comparing the survey estimate numbers at age over time (e.g., relative abundance at age
2 in year $y$ compared to abundance at age 3 in year $y+1$). 

**Response**: The \gls{stat} did not have sufficient time to address this recommendation and agrees that a future \gls{stat} should work to understand cohort mortality.

**Recommendation**: Better estimates of aging error, bias and continued efforts to improve on age validation remain
high research priorities. 

**Response**: This assessment incorporated an updated ageing error estimate of uncertainty and bias using Template Model Builder, which can account for random effects.  The \gls{stat} agrees that future work should be done to improve age validation to improve our understanding of age-structure in the `r spp` population off the U.S. West Coast.


## Model Structure and Assumptions

### Modeling Platform and Structure

This assessment was conducted using Stock Synthesis version 3.30.24 developed by Dr. Richard Methot at the NOAA, NWFSC [@MethotWetzel2013]. This most recent version was used because it included improvements and corrections to older model versions. The previous assessment of sablefish used an earlier version of Stock Synthesis (3.30.21). Model bridging was performed between both versions of Stock Synthesis and discussed below. The `R` package `r4ss`, version 1.51.0, along with `R` version 4.4.1 were used to investigate and plot model fits.

### Model Selection and Evaluation

The base assessment model was developed to balance parsimony and realism to ultimately achieve a robust and stable model structure. The goal was to estimate stock size, stock status, and related reference points (e.g., spawning output trajectory) for the population off the West Coast of the U.S. The model contains many assumptions to achieve parsimony and uses many different sources of data to estimate reality. A series of investigative model runs were done to achieve the base model.

### Model Changes from the Last Assessment {#changes}

A number of data and modeling changes were made in this assessment relative to the previous benchmark assessment [@haltuch_status_2019]:

- All available data were reprocessed and extended through 2024.
- Hook-and-line and pot gear were split into separate fleets whereas the previous assessment combined these data into a single fixed gear fleet.
- The index and age data from the \gls{s-aslope} were not included in the base model due to issues with the age data.
- The \gls{s-tri} was split into two separate survey fleets, each with indices and estimates of catchability and selectivity.  The early period ranged from 1980--1992 and the late period 1995--2004.  The previous assessment split the survey with a change in catchability and selected selectivity parameters between the early and late period. Splitting this survey into two separate fleets allowed for period-specific estimation of selectivity and separate data weighting. Additionally, select years of age data were excluded due to concerns that they were not representative due to limited spatial coverage across tows.
- This assessment incorporated a new shorter environmental index to inform the estimates of recruitment.  The previous assessment used an environmental index based upon sea surface height from 1925--2018.  The new environmental index were based on a GLORYS model informed by a number of environmental covariates that ranged from 2020--2024. This newer index approach was selected since the estimation of historical recruitments should be well informed by data and that recruitment near the end of the model period can be the most uncertain due to limited observations.
- An new evaluation of ageing error was conducted and the assumed bias and uncertainty were updated.
- This assessment incorporates new research on maturity moving from maturity-at-length to maturity-at-age. The coastwide maturity-at-age vector was estimated using a spatial modeling approach that supported the development of a biomass-weighted maturity curve to better account for variation in maturity-at-age by area north and south of 36$^\circ$ N. latitude.
- Empirical weight-at-age was used in this assessment to account for time-varying growth by age, sex, and year.
- The prior assumed for $M$ was updated based upon new research.
- $M$ continues to be estimated, but is estimated to be equal between female and males.
- Steepness ($h$) continues to be fixed at an assumed value. However, due the lack of research on sablefish productivity and resiliency, $h$ is fixed at 0.75 in this assessment to align with the proxy reference points used for management of the stock off the U.S. West Coast. The previous assessment fixed $h$ at 0.70.
- This assessment opted to model removals via discard fleets for each gear type. The discard fleet approach was considered to be more transparent, allowing separate selectivity for retained and discarded fish, and improved model stability.
- This assessment simplified the modeling of changing selectivity (e.g., blocks) due to management changes where possible.
- Annual recruitment deviations were estimated starting in 1975 with recruitment between 1890--1974 assumed to be equal to be equal to the stock-recruitment curve.
- Recruitment deviations were estimated as simple deviations (recruitment deviation option two in Stock Synthesis) rather than a deviation vector with a sum to zero constraint (option one in Stock Synthesis).


### Key Assumptions and Structural Choices

The specifications of the assessment are listed in @tbl-model-config. The model is a two-sex, age-structured model starting in 1890 with an accumulated population age group at 70 years. $M$ was estimated and assumed to be time invariant and equal between males and females.  An empirical weight-at-age approach was implemented with sex-specific time-varying growth between 2003--2024.  The ages in the population were tracked by 1 year intervals between 0--70 years of age and the age data were grouped by age between 0--50 with 50 being used as data plus group.  Summary biomass was calculated for ages 3 plus. The sablefish population off the U.S. West Coast was modeled as a single area with only one season per year and coastwide time-varying growth pattern by sex via the weight-at-age approach. 

Selectivity was age-based and modeled by fleet (retained/total removals and discard fleets) with time blocks on selectivity to allow for shifts in selectivity for each fishery fleet. The selectivity between hook-and-line and pot gears were mirrored (e.g., data combined to estimate selectivity for both gear types) due to similarity in the composition of retained age data between the gears.  The trawl fleet and each of the discard fleets (trawl, hook-and-line, and pot) estimated fleet-specific selectivities. The mirrored hook-and-line and pot fleets also allowed for sex-specific selectivity with females having a higher selectivity by these gears compared to males. The trawl, hook-and-line, and pot gears had time blocks between 1890--2001 and 2002--2024 to account for the implementation of the \gls{rca} that eliminated fishing in select depth ranges across the coast. It is important to note that many \gls{rca} were opened for groundfish fishing in 2024, but with only one year of data, an additional time block starting in 2024 was not included in the base model. Future updates to this model should explore adding a time block starting in 2024 to determine if there were changes in selectivity arising from the opening of \gls{rca}. The trawl and hook-and-line discard fleets assumed three time blocks: 1890--2010, 2011--2018, and 2019--2024 to account for implementation of the \gls{ifq} system in 2011 and the change by management to credit quota accounts in the \gls{ifq} fishery for discarded sablefish that were assumed to have survived based upon discard mortality rates which led to changes in discarding practices.  The pot discard fleet assumed two time blocks: 1890--2010 and 2011--2024, with early model development determining that an additional block for 2019--2024 had little to no impact on the model fits to the age data for this fleet. 

The specification of when to estimate recruitment deviations is an assumption that influences not only the estimate of model uncertainty around stock scale and status during that period but also the fits to composition data. Extensive model explorations were conducted to determine the appropriate range of years to estimate recruitment deviations. This assessment opted to not include recruitment deviations early in the model period, when data were not available, and begun estimation in 1975 based upon when the estimates appeared to be informed by data. The earliest age-composition data began in 1983. The estimates of recruitment deviations from 1975--2023 were considered within the "main period" and 2024 as the "late period" within Stock Synthesis. A bias adjustment was applied between 1974--2024 and no bias adjustment was applied during the projection period (i.e., 2025--2036). @methot_adjusting_2011 summarize the reasoning behind varying levels of bias adjustment based on the information available to estimate the recruitment deviations. The standard deviation of recruitment variability was assumed to be `r sigma_r` based on the estimated variation in recruitment from the base model.

The following distributions were assumed for fitting data: survey indices were log-normal; the environmental index was normal, and the age-composition data followed a multinomial error structure.

### Estimated and Fixed Parameters

There were 99 estimated parameters in the base model. These included one parameter for $R_0$ parameterized in log-space, one parameter for $M$, two parameters for extra variability for the late Triennial and NWFSC slope survey indices, one parameter for catchability for the recruitment index, 32 parameters for age-based selectivity and time blocking of the fishery and the survey fleets, 50 recruitment deviations, and 12 projected recruitment deviations (@tbl-n-param). 

Fixed parameters in the model were as follows. Steepness was fixed at `r h`. Maturity-at-age was fixed in the model and fecundity was assumed equal to body weight. Sex-specific empirical weight-at-age by year was estimated external to the model to account for growth variation by year, area, sex, and age. The standard deviation of recruitment deviates was fixed at `r sigma_r`, the same value assumed in the last assessment.  

Specific selectivity parameters were estimated for all fishery and survey fleets in the model. All fleets were allowed to estimate dome-shaped selectivity.  The selectivity between the hook-and-line and pot fleets were assumed equal (e.g., mirrored) and incorporated sex-specific selectivity with females being more selected compared to males. The trawl fleet, all three discard fleets, and survey fleets assumed equal selectivity for females and males. The decision about whether to mirror selectivity among fleets and whether to allow for sex-specific selectivity was based upon explorations of the data and model testing. The recruitment index was modeled as a recruitment deviation survey within Stock Synthesis which assumes the index is representative of age-0 fish.  

### Priors

A prior was used for $M$ in the base model. The base model estimated $M$ with a prior distribution based on the @hamel_development_2022 meta-analytic approach with an assumed maximum age of 75 years for both males and females. The prior assumed a log-normal distribution for $M$. The log-normal prior has a median of 0.072 yr$^{-1}$ and a standard error of 0.31. The prior was assumed the same for each sex during early model development with the base model estimating a single $M$ for both sexes.

The treatment of $h$ has varied across recent assessment given the lack of research about sablefish productivity and resiliency. The assessment conducted in 2007 estimated $h$ = 0.43, the 2011 assessment fixed $h$ at 0.60 based upon @he_prior_2006, and the 2019 assessment assumed a fixed value of 0.70. This assessment opted to fix $h$ at `r h`. A sensitivity was done where $h$ was estimated with a prior using a beta distribution with mean of `r h` and standard error of 0.15 (see Section \ref{sensitivities}). A value of `r h` was selected and based upon the range of values that appeared to be supported based upon data and current understanding about life history. Additionally, a value of `r h` aligns with \gls{pfmc} adopted reference points for sablefish. 

### Data Weighting

Age data from each fishery and survey fleet were fit and appropriately weighted within the model. Age data started with a sample size determined from the equation listed in Section  \ref{fishery-bds-data} for fishing fleets in the model. Input sample sizes for survey age data were calculated according to the method described in Section \ref{wcgbt-data}. 

The base model was weighted using the Francis method, which was based on equation TA1.8 in Francis [@francis_data_2011]. Sensitivities were performed examining the difference between the McAllister Ianelli [@mcallister_bayesian_1997] method (Harmonic Mean weighting) and the Francis data weighting. The weights applied to the age data by fleet for the base model are shown @tbl-data-weights.

Extra variability parameters were estimated and added to the input variance for the indices of abundance for two surveys in the model: 1) the late \gls{s-tri} (1995--2004) and 2) the \gls{s-nslope}. Estimating additional variance for the early \gls{s-tri} (1980--1992) was explored but not found to be necessary.  The \gls{s-wcgbt} is considered to sample sablefish off the U.S. West Coast well and no additional variance was estimated to ensure that the model fit this index. Estimating additional variance for the \gls{s-wcgbt} was explored during model development resulting in the model estimating ~0.10 added variance. The overall stock trajectory was similar across the time series between the model with and without added variance for the \gls{s-wcgbt}, but the overall fit to the index was poorer when added variance was allowed which led to it not being included in the base model.


### Bridging Analysis {#bridging}

An extensive bridging analysis was conducted to detail the transition from the previous assessment to the base model.  The bridging analysis is presented in three sections: 1) updating the version of Stock Synthesis used, 2) data updating and minor model structure changes, 3) major model structure changes. Updating the version of Stock Synthesis did not result in changes to estimated parameters or derived spawning output (@fig-ss3-version).

Extensive changes to the data and the model structure were targeted to improve model stability (i.e., estimating informed parameters towards balancing bias and variance), which made it challenging to develop a single, simple and transparent bridging process. The data bridging process, where data were reprocessed and updated through 2024, was conducted in an additive fashion. However, many of the model structure changes were often not made in a completely linear fashion during development of the base model. In the bridging presented, changes were grouped for clarity, particularly within the major model structure bridging section, and may not be presented in the order that they were originally decided during modeling development. This non-linear model development and the needed linear bridging has led to some steps in the bridging process to show larger changes in model estimates compared to what was observed when these model structure or parameter changes were decided. Given this, it is recommended to consider both the bridging and the sensitivities for the base model in tandem (see Section \ref{sensitivities} for base model sensitivities).     

The order of data updating and minor model structure changes were:

\begin{enumerate} 
\item Remove the sea surface height environmental index.
\item Update landings for trawl and fixed gears from 1890--2022 and add new landings 2023--2024.
\item Reprocess fishery ages from 1983 -- 2022 and add new ages from 2023--2024.
\item Reprocess fishery discard rates for trawl and fixed gears from 2002--2021 and add 2022.
\item Reprocess fishery discard lengths and mean body weights for trawl and fixed gears from 2002--2021 and add 2022.
\item Split landings, discard, and age data from the fixed gear fleet into two separate fleets: hook-and-line and pot gears.
\item Revise and fix selectivity and retention blocks based upon data and extend through 2024.
\item Reprocess indices of abundance and age composition data from the \gls{s-tri}, \gls{s-aslope}, and \gls{s-nslope}.
\item Reprocess and extend the index of abundance, length compositions, and conditional-age-at-length data from the \gls{s-wcgbt}. 
\item Update maturity from maturity-at-length to maturity-at-age based upon new research.
\item Update the $M$ prior for female and males with a median of 0.072 yr$^{-1}$ and a standard error of 0.31. Continue to estimate sex-specific $M$.
\item Update the ageing error bias and uncertainty using available double-read information through 2024.
\end{enumerate} 

Removing the sea surface height environmental index and updating and extending landings had limited impact on the estimated summary biomass and stock status (@fig-data-bridge-summary-1 and @fig-data-bridge-depl-1). Reprocessing and extending the fishery ages reduced the overall scale of summary biomass and reduced the stock status across all model years. Data and model explorations determined that the change in estimates from the 2023 assessment was due to inclusion of additional historical ages (i.e., 1983---2010) that were not included in previous assessments. The distribution of previously excluded and all the ages used in this assessment were similar (@fig-age-comp) indicating that the change in model estimates were due larger sample sizes rather than changes in the age distribution.  @tbl-fixed-age-samples-comp compares the number of ages by year and gear group between this assessment and the 2019 assessment. The revised age data primarily was collected in Oregon and was excluded due to the lack of information about the ageing method (e.g., break and burn, surface read, etc.) or were marked as special samples in the \gls{odfw} database. After conversations with staff at \gls{odfw} and \gls{cap}, it was determined that the ageing methodology has been generally consistent across time for sablefish and that these samples were likely determined via break-and-burn methods, consistent with current methodology. It further was determined that records marked as special samples in early years of \gls{pacfin} data were randomly collected market samples similar to current sampling programs and that these data should be included in the assessment.  

Reprocessing and extending the fishery discard rates resulted in a reduced estimate of spawning output and stock status across the time series compared to the previous model (e.g., +fishery ages model, @fig-data-bridge-summary-1 and @fig-data-bridge-depl-1). The methodology used for determining discard rates was improved for this assessment compared to previous assessments, which resulted in modest increases in the discard rates primarily for the fixed gear fleet (e.g., hook-and-line and pot, see Section \ref{discards} for additional information). Reprocessing and extending the mean discard weights and length compositions resulted in only minor changes to model estimates. 

Splitting hook-and-line and pot gear landings, discard, and age composition data into separate fleets resulted in generally small decreases to the estimated spawning output and stock status. During the process of splitting out hook-and-line and pot gear fleets, some issues were identified with the time blocks applied to the fishery selectivity and retention parameters resulting in some time-varying parameters being estimated in the absence of data (age or discard length compositions). Hence, blocks were simplified accordingly to ensure data were available to inform estimates. Finally, the blocks were extended through 2024. These fixes  resulted in an increase estimated stock size and stock status compared to the previous model (e.g., Split Fixed Gear, @fig-data-bridge-summary-1 and @fig-data-bridge-depl-1). Reprocessing historical survey based on current best practices resulted in only minor changes in model estimates. Reprocessing and extending the index of abundance, length compositions, and conditional-age-at-length data from the \gls{s-wcgbt} slightly reduced estimated stock size across the time series but had limited impact on the estimated stock status. Adding the new maturity-at-age changed the scale of stock size across the time series but did not change the stock status (@fig-data-bridge-summary-2 and @fig-data-bridge-depl-2). The final two revisions in the data bridging section, updating the prior for $M$ (i.e., continuing to estimate $M$) and the ageing error bias and uncertainty resulted in only minor changes to model estimates.

In summary, across the data bridging, including all available age data had the largest impact on model estimates.  The new discard rates that incorporated an improved methodology to calculate gear-specific discarding across fishery sectors resulted in the next most influential change to model estimates.  

This assessment made a number of structural changes to the model. The order of major structural and data changes were:

\begin{enumerate}
\item Move to start of the main period for estimated annual recruitment deviations in 1975 from 1925 (used in the previous assessment) to align with the period of available data to inform estimates of recruitment and start estimating recruitment deviations at the start of the model (1890) rather than before the first years in the model.
\item Estimate annual recruitment deviations starting in 1975 (e.g., no annual recruitment deviations between 1890--1974).
\item Remove the index of abundance and age composition data from the \gls{s-aslope}.
\item Split out foreign catches from the domestic trawl, hook-and-line, and pot fleets and replace discard lengths with the estimated discard ages. The model has six fishery fleets: three domestic fleets that estimate age-based selectivity and retention, and three foreign fleets that mirror the age-based selectivity for the corresponding domestic fleet by gear.
\item Split the \gls{s-tri} survey into two separate survey fleets in the model and remove select years of non-representative age composition data in the early and late periods.
\item Revise fixed and estimated selectivity parameters for the \gls{s-wcgbt} to better fit the age composition data.
\item Switch to a discard fleet approach where discard mortality is estimated outside the model and included as separate fleets. The model now has six fishery fleets: three removal fleets and three discard fleets by gear type.
\item Include empirical weight-at-age and remove parameters estimating growth.
\item Estimate a single $M$ for both females and males.
\item Update the assumed $h$ from 0.70 to 0.75.
\item Add new recruitment index and estimate annual recruitment deviations as simple deviations.
\end{enumerate}

The 2019 assessment introduced a sea surface height index to inform the estimation of annual recruitment and the model structure of that assessment defined the main period of recruitment to range from 1925--2018. In Stock Synthesis, a user defines three recruitment periods: early, main, and late. The general guidance for defining recruitment periods is that the main period should be years when annual recruitment deviations are well informed by the data (e.g., lower uncertainty intervals). Additionally, the 2019 assessment opted to model annual recruitment deviations with the constraint that the vector of main period deviations sum to zero (e.g. option 1 in Stock Synthesis). During early model explorations it was determined that the decision to start the main period in 1925 combined with the sum to zero constraint had a non-trivial impact on the overall model estimates. Adjusting the main period for recruitment deviation estimation from 1925 to 1975, when annual recruitment deviations were well informed by the data, increased the estimated stock size between 1890--2000 (@fig-structure-bridge-summary-3) and led to a more depleted population at the end of the time series (@fig-structure-bridge-depl-3). Additionally, during the early period of the time series there was a notable drop in the stock size by 1960 and then a sharp increase in stock size peaking in the mid-1970s that was not due to catches, but mostly due to recruitment deviations. The annual recruitment deviations from the the ageing error model, which retains the 2019 parameterization for early and main period for deviations, were generally more positive and less negative compared to the models that adjusted the period for main deviations (@fig-structure-bridge-rec-dev-3).  This difference in the estimation of the annual recruitment deviations is likely not driven by data but rather the sum to zero constraint across the extended main recruitment estimation period. In order to simplify the model and to only estimate data driven trends in the time series, early recruitment deviations were not estimated in the base model. Sensitivities to this decision are presented in Section \ref{sensitivities}.          

@fig-structure-bridge-summary-4 and @fig-structure-bridge-depl-4 show the impact of models that remove data from the \gls{s-aslope}, split out foreign catches (i.e., selectivity mirrored to domestic gear specific fleets) and estimate age-based selectivity and retention, and split the \gls{s-tri} and remove select years of age data. There was limited impact on the model estimates from removing the \gls{s-aslope} data and splitting out the foreign catches and moving to age-based retention. Splitting the \gls{s-tri} and removing select years of age composition data reduced the estimate of summary biomass across the time series, but had only a minimal impact to the estimated stock status.  
 
The next steps in the bridging process revised the selectivity for the \gls{s-wcgbt} and changed the model structure to a discard fleet approach (@fig-structure-bridge-summary-5 and @fig-structure-bridge-depl-5).  Optimizing the estimated and fixed parameters for the \gls{s-wcgbt} decreased the estimate of summary biomass and resulted in a more depleted population compared to the previous model in the structure bridging (e.g., split \gls{s-tri}). The parameterization for this survey in the previous assessment assumed a steep dome-shaped selectivity with a plateau in selectivity around ~ 0.45 for ages 10 and older (see Figure 53 in @haltuch_status_2019). During model explorations for this assessment, all parameters from this survey were estimated to provide flexibility for the selectivity shape to change based upon the data and, subsequently, parameters were fixed at the estimates as necessary (e.g., parameters at inconsequential bounds or containing large uncertainty).  During this exploration the data supported a steep increase in selectivity between age-0 and age-1, maximum selectivity at age-1, and only a limited dome with a plateau of selectivity for age 3 and older around ~ 0.8. The \gls{s-wcgbt} samples  much of the depth range for sablefish (sampling between 55--1,280 m), and the survey is believed to be representative and informative of the sablefish population off the West Coast. The resulting selectivity shape was more in line with *a priori* expectations for this survey. Removing the estimation of retention and adding discard fleets marginally increased the estimate of summary biomass at the start of the time series and marginally decreased it at the end of the times series when compared to the previous bridging model (@fig-structure-bridge-summary-5). 

The final bridging steps included adding time-varying growth through the use of empirical weight-at-age data, assuming a single $M$ value for both sexes, updating the fixed $h$ value to `r h`, and adding the recruitment index with the simple deviation approach used in Stock Synthesis (@fig-structure-bridge-summary-6 and @fig-structure-bridge-depl-6). Estimates of stock size and stock status were relatively similar across models. Switching to an empirical weight-at-age approach slightly increased the estimate of stock size across the time series. Revising the assumption around $h$ reduced the estimates of stock size at the start of the time series. The estimated stock status was similar across these models.

In summary, across all the model structure bridging steps, revising the treatment of recruitment deviations (i.e., changing the defined main period) and the selectivity for the \gls{s-wcgbt} had the largest impact on model estimates. Both of these changes were considered improvements to the model structure by improving the fits to data while aligning with modeling best practices. A comparison of the base model to the 2023 model, and earlier assessments, is provided in Section \ref{historical}.