## Modeling Results

Parameters were estimated using maximum likelihood estimation and uncertainty is based on the assumption of asymptotic multivariate normality of the maximum likelihood estimate, where the variance-covariance matrix is the inverse of the hessian matrix. A list of fixed and estimated parameters in the model and asymptotic standard error estimates for estimated parameters is available in @tbl-param. The negative log likelihood components by data type are shown in @tbl-likes. Estimates of derived reference points and approximate 95 percent asymptotic confidence intervals are shown in @tbl-ref-points. Estimates of stock size and other key population metrics over time are shown in @tbl-ts.

### Parameter Estimates

The $M$ for both females and males was estimated as a single parameter. $M$ was estimated to be `r m[1]` yr$^{-1}$ using a prior with a median of 0.072 yr$^{-1}$ and a standard error of 0.31 (@tbl-param and @fig-m-est-prior). Sensitivities to the treatment of $M$ are shown in Section \ref{sensitivities}.

Age-based selectivity curves were estimated for the fishery and survey fleets using the double-normal selectivity parameterization in Stock Synthesis. The selectivity curves for the hook-and-line and pot gears were sex-specific while all other fishery and survey fleets were parameterized to have a single selectivity curve for both sexes. The estimated selectivity curves are shown in @fig-fishery-selex and @fig-survey-selex. The selectivity for the trawl, hook-and-line, and pot gears (recall the pot and hook-and-line gears were mirrored) were estimated to be dome-shaped with each fleet estimating small changes in selectivity between 1890--2001 and 2002--2024. The dome in the trawl selectivity between 2002--2024 shifts rightward, increasing peak selectivity for older fish compared to 1890--2001. The selectivity was assumed to be equal for the hook-and-line and pot gears with higher selectivity for females compared to males. The selectivity for hook-and-line and pot gears peaked at older ages and had lower selectivity at the oldest ages when compared to trawl gear selectivity. 

Three selectivity periods were estimated for the trawl and hook-and-line discard fleets: 1890--2010, 2011--2018, and 2019--2024 (@fig-fishery-selex). The selectivity for the trawl discard fleet was estimated to be sharply domed with discarding peaking for young fish followed by a rapid decline to a lower level of discarding for older fish in each time period. The hook-and-line discard fleet estimated dome-shape selectivity to peak between 3--5 years of age depending upon the time block. The selectivity for the pot discard fleet has time blocks between 1890--2010 and 2011-2024 that show a peak occurring between 3--6 years of age, but with a higher frequency of discarding older fish compared to the hook-and-line discard fleet.    

The estimated selectivity for the separate early and late periods of the \gls{s-tri} were domed with the survey primarily selecting only young fish (@fig-survey-selex). The early period of the \gls{s-tri}, 1980--1992, sampled depths ranging form 55--366 m and was estimated to have full selectivity for ages 1 to 3, limited selectivity for age 4, and very low selectivity for older ages (e.g., 0.005). The late period of the \gls{s-tri}, 1995--2004, extended the sampling out to depths of 500 m.  The estimated selectivity for the late period peaked at age 2 and then declined from ages 3 to 6 before settling at a low selectivity for older ages (e.g., 0.02). The estimated selectivity for the \gls{s-nslope} was estimated to be slightly domed, peaking at age 4 and then declining slightly around age 5 and 6 before plateauing to a constant level for older ages (@fig-survey-selex). The selectivity curve for the \gls{s-wcgbt} was similar to the selectivity for \gls{s-nslope}, with the survey having limited selectivity for age-0 fish but then quickly peaking at age 1 before decreasing slightly by age 2 to a constant plateau for older ages (@fig-survey-selex). The selectivity of age-0 fish, the steep increase, limited width at the peak, and the steep decrease in selectivity for the \gls{s-wcgbt} led to issues with parameters being estimated at parameter bounds requiring many of the selectivity parameters to be fixed. Future update and benchmark assessments for sablefish should evaluate if fixed parameters need to be revised based upon new data in order to retain the best fit to the survey data.     

Catchability for each of the surveys was analytically derived by comparing observed to expected vulnerable biomass across all years for each survey. The catchability for the early and periods of the \gls{s-tri} was `r q[1, "Value"]` and `r q[2, "Value"]`, respectively (@tbl-param). The catchability for the \gls{s-nslope} was `r q[3, "Value"]` and `r q[4, "Value"]` for the \gls{s-wcgbt}.  The catchability for the recruitment index was an estimated parameter, but its interpretation is not as intuitive as it is for abundance indices.  The estimate for this index was `r q[5, "Value"]`.

Process error was added directly to each years input standard deviation for the late period of the \gls{s-tri} and \gls{s-nslope} as additional survey variability. The added standard deviation for each of these surveys was `r survey_add_sd[2, "Value"]` and `r survey_add_sd[3, "Value"]`, respectively (@tbl-param).  No additional survey variability was needed to fit the trend in the early period of the \gls{s-tri}. No additional survey variability was estimated for the \gls{s-wcgbt}, because this survey is largely considered an effective sampling tool for sablefish and identified as a key data source that the model needed to fit. 

The time series of estimated recruitments and annual recruitment deviations are shown in @fig-recruits and @fig-recdevs. Years with the highest recruitment deviations were estimated to have occurred in `r top_recdevs[1, "years"]`, `r top_recdevs[2, "years"]`, `r top_recdevs[3, "years"]`, `r top_recdevs[4, "years"]`, and `r top_recdevs[5, "years"]`. The lowest annual recruitment deviations (e.g., negative deviations) were estimated to have occurred in `r low_recdevs[1, "years"]`, `r low_recdevs[2, "years"]`, `r low_recdevs[3, "years"]`, `r low_recdevs[4, "years"]`, and `r low_recdevs[5, "years"]`. Initial model explorations found that there was limited information in the data to inform annual recruitment deviations prior to 1975, often leading to a source of model instability.  Thus, deviations for years prior to 1975 were not estimated in the base model. Estimated recruitment deviations during years with the majority of the age data (i.e., after 1990) have relatively low uncertainty intervals indicating support in the data for strong or poor recruitment years. The estimated annual recruitment deviation in 2024 is uncertain, but estimated to be above average based upon age 0 data from the \gls{s-wcgbt} and the recruitment index. The recruitment bias adjustment applied within the model across years is shown in @fig-biasramp.

### Model Fits

The fit to the survey indices are shown in @fig-index-fit-early-triennial -- @fig-index-fit-wcgbt. The model fit the early period for the \gls{s-tri} well.  The late period for the \gls{s-tri} had an increasing trend in the index that the model generally fit, although additional survey variability was estimated in order to fit the 1998 and 2001 data points. The model fit the trend in the \gls{s-nslope} index between 1999--2001, but estimated a higher vulnerable biomass in 1998 and then lower in 2002 relative to the index. The model fit the trend in the \gls{s-wcgbt} index for most years, but the model trend for the 2019 (above) and 2022 (below) data points was outside the uncertainty interval. The fit to the recruitment index generally followed the trend in the annual data points (@fig-index-fit-enviro). 

Fits to the age data are shown based on the proportions of age observed across all years and the Pearson residuals-at-age for all fleets. Age composition aggregated fits by fleet are reasonably well fit and are shown in @fig-aggregate-age-fit. The residuals for the trawl fleet did not show clear patterns or periods of misfit by sex (@fig-pearson-trawl), however, there appeared to be some pattern of observations being greater than the model expectations that move through the age distribution across years likely due to strong recruitments.  The model fits the general trend in the mean ages for sexed fish, particularly between 2014 onward (@fig-mean-age-trawl). Similar to the trawl data, there was some patterns in the residuals for the hook-and-line data that move through the age classes across years, but aside from that, there were no other clear patterns of misfit for the hook-and-line data (@fig-pearson-hkl). Extensive explorations in blocking of selectivity parameters were done in attempt to reduce the residual pattern across ages in the final block, 2019--2024, but a better fit to the data was not found. The residual pattern in this period is more prominent for females, likely due to the higher selectivity for females compared to males in this fishery. The pattern in mean age of the hook-and-line data was generally fit by the model, with the model estimating subtle decreases and increases in the mean age that aligns with the trend in the data (@fig-mean-age-hkl). There was a slight pattern in the residuals for pot gear between 1986--1990 with greater observations compared to model expectations, but this is also the period when the age data were the most limited for this fleet (@tbl-pot-age-samples and @fig-pearson-pot). The mean ages across years for the pot fleet has large confidence intervals with the model generally fitting the trend for most years except for the increase in the mean age between the late 1980s and early 1990s (@fig-mean-age-pot).     

The aggregated age compositions for the discard fleets were generally well fit (@fig-aggregate-age-fit). The majority of discard ages from the trawl discard fleet were young fish. There is a large residual in the trawl discard ages in 2022 at the youngest ages, likely due to the large 2020 and 2021 cohort (@fig-pearson-trawl-discards). The model fit the decline in the mean ages between 2008 and 2009 in the trawl discard fleet (@fig-mean-age-trawl-discards). The majority of trawl fishing and discarding since 2011 is from \gls{ifq} vessels, where discarding has been low and generally of young, small fish as observed in the data. There are no clear patterns of residuals in the hook-and-line discards (@fig-pearson-hkl-discards) and pot discards (@fig-pearson-pot-discards). The mean age from the hook-and-line discard fleet was older on average compared to the trawl discard fleet. The predicted fit was within the uncertainty interval for all years for both the hook-and-line and pot discard fleets, but the model did not closely track the mean age across years (@fig-mean-age-hkl-discards and @fig-mean-age-pot-discards). 

For the \gls{s-tri}, in 1983 and 1989 there was slight over-fitting for females and under-fitting of males and a general good fit in 1992 (@fig-pearson-tri-early). The model fit the mean age for 1983, 1986, and 1992, though it was generally flat over the survey period (@fig-mean-age-tri-early). For the late period of the \gls{s-tri}, the largest residuals indicated that there were more older ages observed than expected in 1995 compared to 2004 (@fig-pearson-tri-late). The base model predicted a drop in mean age for this survey between 1995 and 2004 which matched the trend for mean age in the data (@fig-mean-age-tri-late). The model fit the age data from the \gls{s-nslope} with no clear patter in residuals across years (@fig-pearson-nwfsc-slope). The model predicted a larger drop in the mean age between 2001 and 2002 which was not observed in the data from this survey (@fig-mean-age-nwfsc-slope).  

The aggregated age composition for female and male fish for the \gls{s-wcgbt} were fit well by the model (@fig-aggregate-age-fit). There was no clear residual patterns in the fit to the \gls{s-wcgbt} age data (@fig-pearson-wcgbt).  The largest residuals were for unsexed fish at age-0 since the majority of unsexed data for this survey are from fish too small to reliably sex. The model generally under predicted the mean age of the sexed fish between 2006--2016 (@fig-mean-age-wcgbt).  The mean age in the sexed fish has declined in recent years, likely due to multiple years of strong recruitments (e.g., 2016, 2020, 2021, and 2023).   

### Population Trajectory

The predicted spawning output is given in @tbl-ts and plotted in @fig-sb.  The predicted spawning output time series shows a slow decline in spawning output from 1890--1980 and a rapid decline from 1981--2000 from the fishery ramping up with large removals starting in the mid-1970s. Since 2001, spawning output remained at lower levels until approximately 2017 before a sharp increase started in 2018. The recent increase in spawning output is being driven by the the strong 2016 cohort and the proportion of mature fish from the strong 2020 cohort. The summary biomass of fish age 3 and older has an even steeper increase at the end of the time series from both the 2020 and 2021 strong cohorts (@fig-summary-biomass). The estimated total biomass follows a similar trend as the summary biomass but with even a more dramatic increase at the end of the time series, again, due to recent strong cohorts (@fig-total-biomass). Stock status (or relative spawning output) is estimated to have declined below the management target in 1988 and continued to decline until 2013 (@tbl-ts and @fig-depl). Since 2014, stock status has steadily increased due to the 2008 cohort and has continued to increase from additional strong recruitments.  The stock status in `r end_year` is estimated to be `r 100*depl_final` percent, currently below the management target but projected to surpass the management target in 2027 (@tbl-ts).     

The stock-recruit curve resulting from a value of steepness fixed at `r h` is shown in @fig-sb-recr with estimated recruitments also shown. Steepness
was not estimated in this model, but a likelihood profile across steepness values is shown in Section \ref{profiles}.





