
## Model Diagnostics

### Convergence

Proper convergence was determined by starting the minimization process from dispersed values of the maximum likelihood estimates to determine if the model found a better minimum. Starting parameters were jittered using the jitter function with Stock Synthesis, using jitter input of 0.05. This was repeated 100 times with one of the 100 runs returning to the base model likelihood. A better, lower negative log-likelihood, model fit was not found. In the jittering analysis models with similar log-likelihood values (difference < 0.50 units) were often found with little difference in overall derived quantities of stock size and status indicating a relatively flat likelihood surface around the maximum likelihood estimate. Additionally, jitters using a smaller jitter value yielded an increased frequency of runs returning to the base model with no models finding a better fit to the data. Through the jittering done as explained and likelihood profiles, we are confident that the base model as presented represents the best fit to the data given the assumptions made. There were no difficulties in inverting the Hessian for model with discard fleets to obtain estimates of variability, although much of the early model investigation was done without attempting to estimate a Hessian.


### Sensitivity Analyses {#sensitivities}

Sensitivity analyses were conducted to investigate influence of data inputs and structural uncertainty of the base model by investigating how changes to the model affected the estimated values and derived quantities. These include several key underlying structural model assumptions that were identified in previous assessments and STAR panels, have persisted across recent assessments, or arose during the model bridging steps presented in this assessment (see Section \ref{bridging}). Many additional sensitivity runs were conducted while developing and testing the `r end_year` base model. Here we focus on the main sensitivities, relative to the base model, which are as follows:

1. Remove the index and age composition data from the \gls{s-wcgbt},

2. Remove the index and age composition data from the \gls{s-tri},

3. Remove the index and age composition data from the the \gls{s-nslope},

4. Remove the environmental-based recruitment index,

5. Remove empirical weight-at-age data for calculating time-varying growth and instead estimate time-invariant growth within the assessment model,

6. Estimate sex-specific natural mortality (*M*),

7. Fix *M* at the sex-invariant value used in the assessment of `r spp` in Alaska,

8. Fix *M* at a sex-invariant value that is adjusted upwards to offset potential net emigration to Canada,

9. Fix *M* at sex-specific values used in the 2019 U.S. West Coast assessment of `r spp`,

10. Estimate the steepness (*h*) parameter of the stock-recruitment function,

11. Impose a restriction that recruitment deviations in the main recruitment period must sum to zero,

12. Estimate early (1890--1974) recruitment deviations with the sum to zero constraint imposed for the main period,

13. Switch from the Francis method to the McAllister-Ianelli harmonic mean method for weighting age composition data,

14. Force the estimation of asymptotic selectivity for \gls{s-wcgbt} and \gls{s-nslope}, and

15. Remove the updated ageing error vector and apply the vector used in the 2019 stock assessment.

Most of the sensitivities resulted in a similar trajectory of the population dynamics as the base model (@tbl-sens-1 -- @tbl-sens-4; @fig-sens-1-bratio -- @fig-sens-4-recdev), with the largest deviations occurring in the sensitivities related to $M$ and the estimation of early (1890--1974) recruitment deviations.

All sensitivity models matched the base model in terms of the stock trend increasing rapidly from a time series low in the early 2010s. This is in part due to the well above average estimates of recruitment given the stock size (i.e., positive recruitment deviations) in 2013, 2016, 2020, 2021, and 2023. All sensitivity models indicate that stock status at the beginning of `r end_year` is estimated to be at or below $\text{SB}_{40\%}$, with the majority of runs aligning with the base model stock status of `r 100*depl_final` percent. The overall scale of the population was generally robust to alternative sensitivity runs, with the exception of model runs exploring various alternative assumptions about $M$.

Results from the base model were generally robust to the removal of survey data (index and age compositions), with the important exception of the removal of the \gls{s-wcgbt}. Current stock size and status estimates were reduced by approximately 15 percent when \gls{s-wcgbt} data were removed (@fig-sens-1-bratio -- @fig-sens-1-sumB), considerably lowering estimates of recent recruitment (@fig-sens-1-recdev). Furthermore, the stock trend levels off in recent years when ignoring recent \gls{s-wcgbt} data (@fig-sens-1-wcgbt), suggesting that these data are particularly influential on recent stock trends. Overall, the \gls{s-wcgbt} is the most important source of fishery-independent information in this assessment because of its longevity under a rigorous and spatially comprehensive survey design and direct application to recent stock trends. 

The sensitivity of the base model to how growth is incorporated into the the stock assessment model provides contrast between two fundamentally different ways of tracking changes in biomass among survivors from year to year. For reasons outlined in Section \ref{watage}, growth in the base model uses empirical weight-at-age information to directly calculate average changes in biomass due to growth for each sex, age, and year combination. Alternatively, and similar to what was done in previous `r spp` assessments, growth can be estimated within the model itself (see @tbl-sens-3). While stock status was similar between models (@fig-sens-3-bratio), the sensitivity model that estimated growth internally indicated a slightly lower population scale (@fig-sens-3-sumB) and generally minor changes to recruitment deviation estimates (leading to less recruitment variability, especially in recent years; @fig-sens-3-recdev). Recruitment estimates for 2024 were the most sensitive, where the direction of the deviation switched from positive (base model) to negative (sensitivity model).

The largest changes relative to the base model were from different natural mortality (*M*) specifications. Across sensitivities, *M* deviated from the base model estimate of `r m[1]` yr$^{-1}$, ranging from a low of 0.068 yr$^{-1}$  (2019 stock assessment estimate for males) to 0.132 yr$^{-1}$  (increase in *M* to account for potential net emigration to Canadian waters; @tbl-sens-3). In general, higher values of *M* led to considerable increases in population scale and stock status, whereas lower values reduced population scale and stock status (@fig-sens-3-bratio -- @fig-sens-3-sumB). The range of estimates for 2025 stock status were from 26.1 to 40.0 percent, compared to `r depl_final*100` percent for the base model. Recruitment patterns were relatively insensitive to *M*, but the absolute size of recruitment deviations scaled with *M* (@fig-sens-3-recdev). In other words, higher relative values of *M* translated to higher relative recruitment deviations for any given year.

In addition to growth and mortality, assumptions about `r spp` recruitment also influence the underlying biological processes used in an assessment model. Sensitivity models that estimated the parameter for the steepness (*h*) of the stock-recruitment function and constrained the recruitment deviations to sum to zero during the main recruitment period (1975--2023) resulted in little change in model results (@fig-sens-4-bratio -- @fig-sens-4-recdev). This is because estimated $h$ (0.797) was similar to the fixed value in the base model (`r h`; @tbl-sens-4), and the sum of main period recruitment deviations in the base model was already close to zero (`r sum_main_devs`). While estimating early period (1890--1974) recruitment deviations did not appreciably change stock scale or status, it did alter the size and trend in recruitment deviations and the general stock trajectory prior to 1980 (@fig-sens-4-bratio -- @fig-sens-4-recdev).

Many other data and model structure sensitivities were explored during the development and testing of the 2025 base model. In particular, changing the data weighting approach for age composition data from the Francis method to the McAllister-Ianelli method and changing the functional form of selectivity to be asymptotic (logistic) for \gls{nwfsc} surveys had almost no impact on stock size and stock status (@tbl-sens-2; @fig-sens-2-bratio -- @fig-sens-2-sumB). McAllister-Ianelli data weights led to moderately different recruitment deviations, though difference were well within the range of uncertainty for the base model (@fig-sens-2-recdev). Ignoring recent age structure double read data and associated updates to ageing error analyses (i.e., use ageing error information from the 2019 stock assessment) lowered population scale, including the alteration of recruitment estimates, but did not impact relative stock status (@fig-sens-2-bratio -- @fig-sens-2-recdev).    


### Likelihood Profiles {#profiles}

Likelihood profiles were used to elucidate conflicting information among various data sources, to determine how asymmetric the likelihood surfaces surrounding point estimates may be, and to provide an additional evaluation of how precisely parameters are being estimated. Likelihood profiles were completed for three key model parameters: unexploited (unfished) equilibrium recruitment in log-space (*R~0~*), natural mortality (*M*), and steepness (*h*). For a single parameter, an increase in negative log-likelihood of more than two units is considered a definitively worse model and of more than seven units a comparatively implausible model.

Unexploited equilibrium recruitment (*R~0~*) was found to be supported by the data across a range from 9.9-10.4, values which led to a broad range of stock sizes (@fig-r0-profile--@fig-r0-profile-depl). The range of values explored led to large differences in overall scale of the spawning population (@fig-r0-profile-ssb), but relatively small differences in estimates of current stock status (@fig-r0-profile-depl). The largest differences in stock status arose from the 1920s to the 1970s, where there is little information on recruitment during a period with fishing.

Natural mortality (*M*) profiles were conducted on the female *M* parameter only since the base model does not specify sex-specific *M* (i.e., equivalent results for male *M*). In general, *M* was moderately informed across a range of values spanning from about 0.080 to 0.095 yr$^{-1}$ (@fig-m-profile), compared to `r m[1]` yr$^{-1}$ for the base model. Across this range, assessment results varied considerably among these values in the absolute scale of spawning output (@fig-m-profile-ssb). Differences were also apparent on resulting stock status estimates, particularly as it pertains to how fast the population declines early in the time series (@fig-m-profile-depl). While abundance index data had little information content for estimating *M*, age data from the trawl fishery and the \gls{s-wcgbt} were the most influential (@fig-m-profile).

In the base model, steepness (*h*) is fixed at `r h`, making it an important profile to evaluate as its uncertainty is not explicitly included in the base-model results. In 2019, *h* was fixed at 0.70. This assessment found no support in any data source for estimating *h* over a broad range of explored values (@fig-h-profile). Structural uncertainty from unknown *h* was well within the parametric uncertainty (95 percent asymptotic intervals) of the base model for both spawning stock size and stock status (@fig-h-profile-ssb and @fig-h-profile-depl, respectively), suggesting that results are relatively insensitive to alternative values of *h*.


### Retrospective Analysis {#retro}

A retrospective analysis was conducted by running the base model with data removed iteratively from 1 to 10 years. All retrospective model runs fall well within the uncertainty estimates from the base model and contain very low values for Mohn's rho (@fig-retro-sb--@fig-retro-depl), suggesting no concerns of a retrospective pattern for key derived management quantities. Similarly, there was little evidence of a retrospective pattern in the estimation of recruitment deviations (@fig-squid-plot). Generally, recruitment is fairly well determined (as defined by the directionality and size of the deviation) by age 2 to 3.  This is consistent with `r spp` being well sampled by the \gls{s-wcgbt} and fisheries at young ages. In a few cases, cohort strength changed direction (i.e., recruitment below average or above average given the stock size) with a new year or two of data (e.g., 2018 and 2022 year classes; see @fig-squid-plot).

