# Acknowledgements {#sec-acknowledgements}

Many people were instrumental in the successful completion of this assessment and their contribution is greatly appreciated. This assessment draws heavily on the text and analyses from previous assessments of sablefish and has benefited greatly from the efforts of all authors contributing to those analyses.

Theresa Tsou (WDFW) provided Washington historical catches and quickly addressed our multiple questions in order to better understand the data. Alison Whitman (ODFW) provided Oregon historical catches, quickly uploaded age data that were critical to this assessment, and was responsive to our numerous questions. E.J. Dick (NWFSC) provided historical catches for California and Brenda Erwin (CDFW) provided timely answers and resolutions regarding California data.

This assessment was greatly benefited from thoughtful input we received during the pre-assessment data workshop. We are thankful to everyone who took time out of their days and potentially time off the water to attend and provide feedback. 

We are very grateful to Patrick McDonald and the team of agers at the Cooperative Ageing Program for their hard work
reading numerous otoliths and availability to answer questions when needed. Curt Whitmire provided survey sampling area analysis that was critical to understanding area sampled and not sampled by the survey. Kayleigh Somers and Kate Richardson provided critical data from the Fisheries Observer Program and helped us understand the data. One of the key data sources in this assessment were information about discarding practices across groundfish sectors.  We are thankful to the numerous observers whom collected these data that allows us to understand discarding. Data collected by fishery observers combined with the data collected by port samplers across the coast help ensure that our assessments are based upon the best available data. 

Finally, we would like to acknowledge the scientists at the Northwest Fisheries Science Center who make our fishery independent survey possible and their dedication to collecting high quality data. There were numerous aspects of this assessment that were made possible (maturity, weight-at-age, etc.) because of the data collected by the West Coast Groundfish Bottom Trawl Survey. The data they collect is critical in the development of best scientific information available. 
