# Tables 

## Data

```{r}
#| label: tbl-landings
#| warning: false
#| echo: false
#| tbl-cap: "Landings in metric tons (mt) by year for each fleet."

landings <- model_output[["catch"]] |>
  tibble::as_tibble() |>
  dplyr::filter(Yr > 1889) |>
   dplyr::select(Fleet_Name, Yr, ret_bio) |>
   dplyr::group_by(Yr) |>
   dplyr::mutate(
     Yr = as.factor(Yr),
     ret_bio = round(ret_bio, 0),
     `Total Catch` = sum(ret_bio)
   ) |>
   tidyr::pivot_wider(
     names_from = Fleet_Name,
     values_from = ret_bio
   ) |>
  dplyr::rename(
    Year = Yr,
    `Trawl` = Trawl,
    `Hook-and-Line` = Hook_and_Line,
    `Pot` = Pot,
    `Trawl Discard` = Trawl_Discard,
    `Hook-and-Line Discard` = Hook_and_Line_Discard,
    `Pot Discard` = Pot_Discard
  ) |>
  dplyr::relocate(`Total Catch`, .after = `Pot Discard`) |>
  dplyr::ungroup()
kableExtra::kable(
  landings, 
  format = "latex", 
  longtable = TRUE,
  booktabs = TRUE,
  format.args = list(big.mark = ","),
  column_spec = "1.85cm",
  caption = "Removals in metric tons (mt) by year for each fleet.",
  linesep = "") |>
  kableExtra::kable_styling(
    latex_options = "repeat_header",
    font_size = 8)
    
```

\pagebreak


```{r, results = "asis"}
#| label: tbl-management
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: !expr if(eval_tables) recent_management_cap 
#| tbl-pos: H

recent_management_table |>
  gt::gt() |>
  gt::fmt_number(
    columns = 2:6,
    decimals = 0
  ) |>
  gt::tab_options(
    table.font.size = 12 
  ) |>
  gt::cols_align(
    align = "center"
  ) |>
  gt::cols_width(
    tidyselect::everything() ~ px(75)
  ) |>
  gt::as_latex()

```

\pagebreak


```{r, results = "asis"}
#| label: tbl-discard-rates
#| warning: false
#| echo: false
#| tbl-cap: "Observed discard rates by gear based upon West Coast Groundfish Observer Program (2002-2023) and Pikitch (1985-1987) data."
#| tbl-pos: H

read.csv(here::here("data-processed", "data_commercial_discard_rates.csv")) |>
  dplyr::select(-month, -sd) |>
  dplyr::rename(
    Year = year,
  ) |>
  dplyr::mutate(
    fleet = dplyr::case_when(
      fleet %in% c(1, 4) ~ "Trawl Discard Rate",
      fleet %in% c(2, 5) ~ "Hook-and-Line Discard Rate",
      .default = "Pot Discard Rate")
  ) |>
  tidyr::pivot_wider(
    names_from = fleet,
    values_from = discard_rate
  ) |>
  gt::gt() |>
  gt::fmt_number(
    columns = 2:4,
    decimals = 3
  ) |>
  gt::sub_missing(
    columns = tidyselect::everything(),
    missing_text = "-"
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

\pagebreak

```{r}
#| label: tbl-discard-trawl-age-samples
#| warning: false
#| echo: false
#| tbl-cap: "Number of fish, hauls, trips, and calculated input sample size (N) for discard ages from the trawl fleet."

read.csv(here::here("data-processed", "data-discard-sample-sizes-length.csv")) |>
  dplyr::filter(gear_groups == "trawl") |>
  dplyr::select(-fleet_groups, -vessels, -gear_groups) |>
  dplyr::rename(
    Year = year,
    Hauls = hauls,
    Trips = trips,
    Samples = fish,
    `Input N` = input_n
  ) |>
  gt::gt() |>
  gt::fmt_number(
    columns = 2,
    decimals = 0
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

\pagebreak

```{r}
#| label: tbl-discard-hkl-age-samples
#| warning: false
#| echo: false
#| tbl-cap: "Number of fish, hauls, trips, and calculated input sample size (N) for discard ages from the hook-and-line fleet."

read.csv(here::here("data-processed", "data-discard-sample-sizes-length.csv")) |>
  dplyr::filter(gear_groups == "hook-and-line") |>
    dplyr::select(-fleet_groups, -vessels, -gear_groups) |>
  dplyr::rename(
    Year = year,
    Hauls = hauls,
    Trips = trips,
    Samples = fish,
    `Input N` = input_n
  ) |>
  gt::gt() |>
  gt::fmt_number(
    columns = 2,
    decimals = 0
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

\pagebreak

```{r}
#| label: tbl-discard-pot-age-samples
#| warning: false
#| echo: false
#| tbl-cap: "Number of fish, hauls, trips, and calculated input sample size (N) for discard ages from the pot fleet."

read.csv(here::here("data-processed", "data-discard-sample-sizes-length.csv")) |>
  dplyr::filter(gear_groups == "pot") |>
  dplyr::select(-fleet_groups, -vessels, -gear_groups) |>
  dplyr::rename(
    Year = year,
    Hauls = hauls,
    Trips = trips,
    Samples = fish,
    `Input N` = input_n
  ) |>
  gt::gt() |>
  gt::fmt_number(
    columns = 2,
    decimals = 0
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

\pagebreak

```{r}
#| label: tbl-twl-age-samples
#| warning: false
#| echo: false
#| tbl-cap: "Number of sampled trips, age samples, and calculated input sample size (N) by year for the trawl fleet."

read.csv(here::here("data-processed", "data-commercial-age-bds-n.csv")) |>
  dplyr::filter(fleet == "TWL") |>
  dplyr::rename(
    Year = year,
    Trips = trips,
    Samples = samples,
    `Input N` = input_n
  ) |>
  dplyr::select(-fleet) |>
  gt::gt() |>
  gt::fmt_number(
    columns = 2:3,
    decimals = 0
  ) |>
  gt::fmt_number(
    columns = 4,
    decimals = 1
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

\pagebreak


```{r}
#| label: tbl-hkl-age-samples
#| warning: false
#| echo: false
#| tbl-cap: "Number of sampled trips, age samples, and calculated input sample size (N) by year for the hook-and-line fleet."

read.csv(here::here("data-processed", "data-commercial-age-bds-n.csv")) |>
  dplyr::filter(fleet == "HKL") |>
  dplyr::rename(
    Year = year,
    Trips = trips,
    Samples = samples,
    `Input N` = input_n
  ) |>
  dplyr::select(-fleet) |>
  gt::gt() |>
  gt::fmt_number(
    columns = 2:3,
    decimals = 0
  ) |>
  gt::fmt_number(
    columns = 4,
    decimals = 1
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

\pagebreak


```{r}
#| label: tbl-pot-age-samples
#| warning: false
#| echo: false
#| tbl-cap: "Number of sampled trips, age samples, and calculated input sample size (N) by year for the pot fleet."

read.csv(here::here("data-processed", "data-commercial-age-bds-n.csv")) |>
  dplyr::filter(fleet == "POT") |>
  dplyr::rename(
    Year = year,
    Trips = trips,
    Samples = samples,
    `Input N` = input_n
  ) |>
  dplyr::select(-fleet) |>
  gt::gt() |>
  gt::fmt_number(
    columns = 2:3,
    decimals = 0
  ) |>
  gt::fmt_number(
    columns = 4,
    decimals = 1
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

\pagebreak

```{r}
#| label: tbl-twl-age-samples-comp
#| warning: false
#| echo: false
#| tbl-cap: "Change in the number of age samples by year for the trawl fleet between this assessment and the 2019 assessment."

readr::read_csv(here::here("data-processed", "document_sample_sizes_comparison_2019_2025.csv")) |>
  dplyr::select(-`Lengths (2019)`, - `Lengths (2024)`) |>
  dplyr::filter(Year > 1982, Year < 2019) |>
  dplyr::filter(dplyr::case_when(Fishery == "Fixed" ~ Year >= 1986, Fishery == "Trawl" ~ Year >= 1974)) |>
  dplyr::filter(Fishery == "Trawl") |>
  dplyr::arrange(Fishery) |>
  dplyr::mutate(Difference = `Ages (2024)` - `Ages (2019)`) |>
  dplyr::rename(`Ages (2025)` = `Ages (2024)`) |>
  gt::gt() |>
  gt::fmt_number(
    columns = 3:5,
    decimals = 0
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

\pagebreak

```{r}
#| label: tbl-fixed-age-samples-comp
#| warning: false
#| echo: false
#| tbl-cap: "Change in the number of age samples by year for the fixed fleet (hook-and-line and pot gears combined) between this assessment and the 2019 assessment."

readr::read_csv(here::here("data-processed", "document_sample_sizes_comparison_2019_2025.csv")) |>
  dplyr::select(-`Lengths (2019)`, - `Lengths (2024)`) |>
  dplyr::filter(Year < 2019) |>
  dplyr::filter(dplyr::case_when(Fishery == "Fixed" ~ Year >= 1986, Fishery == "Trawl" ~ Year >= 1974)) |>
  dplyr::filter(Fishery == "Fixed") |>
  dplyr::arrange(Fishery) |>
  dplyr::mutate(Difference = `Ages (2024)` - `Ages (2019)`) |>
  dplyr::rename(`Ages (2025)` = `Ages (2024)`) |>
  gt::gt() |>
  gt::fmt_number(
    columns = 3:5,
    decimals = 0
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

\pagebreak


```{r, results = "asis"}
#| label: tbl-prop-area
#| warning: false
#| echo: false
#| tbl-cap: "Estimated percentage of sablefish biomass estimated north and south of 36° N. latitude based on the NWFSC West Coast Groundfish Bottom Trawl Survey data over the last five years."
#| tbl-pos: H

wcgbt_area <- read.csv(here::here("report", "figures", "wcgbt_est_by_area.csv")) |>
  dplyr::filter(area %in%  c("North of Monterey Bay", "South of Monterey Bay")) |>
  dplyr::group_by(year) |>
  dplyr::mutate(
    total_est = sum(est)
  ) |>
  dplyr::mutate(
    Area = dplyr::case_when(area == "North of Monterey Bay" ~ "north", .default = "south"),
    prop = est / total_est
  ) |>
  dplyr::filter(year >= 2019)  |>
  dplyr::rename(
    Year = year,
    Proportion = prop) |>
  dplyr::select(Year, Area, Proportion) |>
  tidyr::pivot_wider(
    names_from = Area,
    values_from = Proportion
  ) |>
  dplyr::mutate(
    Year = as.character(Year)
  ) |>
  as.data.frame()

average <- data.frame(
  Year = "Average",
  north = mean(as.numeric(wcgbt_area[, 2])),
  south = mean(as.numeric(wcgbt_area[, 3]))
)

all <- dplyr::bind_rows(wcgbt_area, average)
colnames(all) <- c(
  "Year", 
  "N. 36 Latitude",
  "S. 36 Latitude"
)

all |>
  dplyr::ungroup() |>
  gt::gt() |>
  gt::fmt_percent(
    columns = 2:3,
    decimals = 1
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

\pagebreak

```{r}
#| label: tbl-wcgbt-strata
#| warning: false
#| echo: false
#| tbl-cap: "Design-based stratification by depth and latitude used to expand composition data for the NWFSC West Coast Groundfish Bottom Trawl Survey."

strata_combo |>
  tidyr::unite(
    "Depth", c(Depth_m.1, Depth_m.2), sep = '-'
  ) |>
  tidyr::unite(
    "Latitude", c(Latitude_dd.1, Latitude_dd.2), sep = '-'
  ) |>
  dplyr::rename(
    `Area (km2)` = area,
    `Depth (m)` = Depth
  ) |>
  dplyr::select(-name) |>
  dplyr::relocate(`Area (km2)`, .after = Latitude) |>
  gt::gt() |>
  gt::fmt_number(
    columns = 3,
    decimals = 0
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

\pagebreak

```{r}
#| label: tbl-wcgbt-samples
#| warning: false
#| echo: false
#| tbl-cap: "Number of tows, positive tows for sablefish, the proportion positive, and the number of age samples by year from the NWFSC West Coast Groundfish Bottom Trawl Survey."

read.csv(here::here("data-processed", "data-survey-wcgbt-n.csv")) |>
  dplyr::select(-N.Lengthed, -Survey) |>
  dplyr::rename(
    Tows = N.Tows,
    `Positive Tows` = Positive.Tows,
    `Prop. Positive` = Proportion.Positive,
    Aged = N.Aged
  ) |>
  dplyr::select(-Sampled.Tows.Lengths) |>
  dplyr::rename(`Sampled Tows` = Sampled.Tows.Ages) |>
  gt::gt() |>
  gt::fmt_number(
    columns = 6,
    decimals = 0
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

\pagebreak


```{r}
#| label: tbl-nwslope-strata
#| warning: false
#| echo: false
#| tbl-cap: "Design-based stratification by depth and latitude used to expand composition data for the NWFSC Slope Survey."

strata_nwfsc_slope |>
  tidyr::unite(
    "Depth", c(Depth_m.1, Depth_m.2), sep = '-'
  ) |>
  tidyr::unite(
    "Latitude", c(Latitude_dd.1, Latitude_dd.2), sep = '-'
  ) |>
  dplyr::rename(
    `Area (km2)` = area,
    `Depth (m)` = Depth
  ) |>
  dplyr::select(-name) |>
  dplyr::relocate(`Area (km2)`, .after = Latitude) |>
  gt::gt() |>
  gt::fmt_number(
    columns = 3,
    decimals = 0
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```


```{r}
#| label: tbl-nwslope-samples
#| warning: false
#| echo: false
#| tbl-cap: "Number of tows, positive tows for samples, proportion of positive tows, and age samples by year from the NWFSC Slope Survey."

read.csv(here::here("data-processed", "data-survey-nwfscslope-n.csv")) |>
  dplyr::select(-N.Lengthed, -Survey) |>
  dplyr::rename(
    Tows = N.Tows,
    `Positive Tows` = Positive.Tows,
    `Prop. Positive` = Proportion.Positive,
    Aged = N.Aged
  ) |>
 dplyr::select(-Sampled.Tows.Lengths) |>
  dplyr::rename(`Sampled Tows` = Sampled.Tows.Ages) |>
  gt::gt() |>
  gt::fmt_number(
    columns = 6,
    decimals = 0
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

\pagebreak


```{r}
#| label: tbl-tri-early-strata
#| warning: false
#| echo: false
#| tbl-cap: "Design-based stratification by depth and latitude used to expand composition data for the Triennial Survey between 1980-1992."


strata_triennial_early |>
  tidyr::unite(
    "Depth", c(Depth_m.1, Depth_m.2), sep = '-'
  ) |>
  tidyr::unite(
    "Latitude", c(Latitude_dd.1, Latitude_dd.2), sep = '-'
  ) |>
  dplyr::rename(
    `Area (km2)` = area,
    `Depth (m)` = Depth
  ) |>
  dplyr::select(-name) |>
  dplyr::relocate(`Area (km2)`, .after = Latitude) |>
  gt::gt() |>
  gt::fmt_number(
    columns = 3,
    decimals = 0
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```


```{r}
#| label: tbl-tri-late-strata
#| warning: false
#| echo: false
#| tbl-cap: "Design-based stratification by depth and latitude used to expand composition data for the Triennial Survey between 1995-2004."

strata_triennial_early |>
  tidyr::unite(
    "Depth", c(Depth_m.1, Depth_m.2), sep = '-'
  ) |>
  tidyr::unite(
    "Latitude", c(Latitude_dd.1, Latitude_dd.2), sep = '-'
  ) |>
  dplyr::rename(
    `Area (km2)` = area,
    `Depth (m)` = Depth
  ) |>
  dplyr::select(-name) |>
  dplyr::relocate(`Area (km2)`, .after = Latitude) |>
  gt::gt() |>
  gt::fmt_number(
    columns = 3,
    decimals = 0
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

\pagebreak

```{r}
#| label: tbl-tri-early-samples
#| warning: false
#| echo: false
#| tbl-cap: "Number of tows, positive tows for samples, proportion of positive tows, and age samples by year from the Triennial Survey (1980-1992)."

  read.csv(here::here("data-processed", "data-survey-triennial-early-n.csv")) |>
  dplyr::select(-N.Lengthed, -Sampled.Tows.Lengths) |>
  dplyr::rename(
    Tows = N.Tows,
    `Positive Tows` = Positive.Tows,
    `Prop. Positive` = Proportion.Positive,
    `Sampled Tows` = Sampled.Tows.Ages,
    Aged = N.Aged
  ) |>
  gt::gt() |>
  gt::fmt_number(
    columns = 6,
    decimals = 0
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

```{r}
#| label: tbl-tri-late-samples
#| warning: false
#| echo: false
#| tbl-cap: "Number of tows, positive tows for samples, proportion of positive tows, and age samples by year from the Triennial Survey (1995-2004)."

  read.csv(here::here("data-processed", "data-survey-triennial-late-n.csv")) |>
  dplyr::select(-N.Lengthed, -Sampled.Tows.Lengths) |>
  dplyr::rename(
    Tows = N.Tows,
    `Positive Tows` = Positive.Tows,
    `Prop. Positive` = Proportion.Positive,
    `Sampled Tows` = Sampled.Tows.Ages,
    Aged = N.Aged
  ) |>
  gt::gt() |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

\pagebreak

```{r}
#| label: tbl-rec-index-aic
#| warning: false
#| echo: false
#| tbl-cap: "Results of model fitting showing estimated coefficients for models with delta AIC </= 2.0. CST = cross-shelf transport, DD = degree days, T = temperature, yolk = yolksack stage, pjuv = pelagic juvenile, and bjuv = benthic juvenile stage."
#| tbl-pos: H

df = data.frame(read.csv(here::here("report", "rda", "Table_dredge-aic-delta4.csv"), header = T))
df = df |> dplyr::filter(delta <= 2)
df = round(df,2)
csums = colSums(df, na.rm = TRUE)
csums = csums[csums!=0]
df = df[,names(csums)]
Model = paste('Model' , 1:nrow(df))
df = cbind(Model,df)
df = df |> dplyr::rename(Intercept = X.Intercept.)
df[is.na(df)] <- ""
r2 = df[3,'R2']

gt::gt(df) |>
  gt::tab_options(
    table.font.size = 10,
    latex.use_longtable = TRUE) |>
  gt::cols_hide(c("weight","logLik","F") )

```

{{< pagebreak >}} 


```{r}
#| label: tbl-afslope-samples
#| warning: false
#| echo: false
#| tbl-cap: "Number of tows, positive tows for samples, proportion of positive tows, and age samples by year from the AFSC Slope Survey."

read.csv(here::here("data-processed", "data-survey-afscslope-n.csv")) |>
  dplyr::select(-N.Lengthed, -Sampled.Tows.Lengths) |>
  dplyr::rename(
    Tows = N.Tows,
    `Positive Tows` = Positive.Tows,
    `Prop. Positive` = Proportion.Positive,
    `Sampled Tows` = Sampled.Tows.Ages,
    Aged = N.Aged
  ) |>
  gt::gt() |>
  gt::fmt_number(
    columns = 6,
    decimals = 0
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

\pagebreak

::: {.landscape}

```{r}
#| label: tbl-watage-samples
#| warning: false
#| echo: false
#| tbl-cap: "Number of ages by sex and year used to estimate the empirical weight-at-age. A plus group of age 25 is shown with all available ages 25 and older combined."

data <- read.csv(here::here("data-processed", "data_weight_at_age_survey.csv")) |>
    dplyr::filter(source == "Groundfish Slope and Shelf Combination Survey") |> 
    dplyr::mutate(
      data_type = "wcgbt",
      age = ifelse(age_years > 25, 25, age_years),
      cohort = year - age,
      sex = tidyr::replace_na(sex, "U"),
      fyear = as.factor(year),
      fcohort = as.factor(cohort)
    ) |>
    dplyr::rename(
      weight = weight_kg
    ) |>
    dplyr::rename_with(.fn = tolower) |>
    dplyr::filter(weight > 0, outlier == FALSE)
  
  remove <- which(data$sex == "U" & data$age != 0)
  data <- data[-remove, ]
  # Randomly assign unsexed age-0 fish to a M or F 50/50
  set.seed(98105)
  
  data |>
    dplyr::group_by(year) |>
    dplyr::mutate(
      age = as.factor(age),
      sex = dplyr::case_when(
        sex == "U" ~sample(rep(c("F", "M"), length = dplyr::n())), .default = sex),
      sex = as.factor(sex)
    ) |>
    dplyr::group_by(year, sex, age) |>
    dplyr::summarize(n = dplyr::n()) |>
    dplyr::arrange(age) |>
    dplyr::arrange(year) |>
    tidyr::pivot_wider(
      names_from = age,
      values_from = n,
      values_fill = 0
    ) |>
    dplyr::rename(
      Year = year, 
      Sex = sex,
      `25+` = `25`
    ) |>
    dplyr::ungroup() |>
  gt::gt() |>
  gt::opt_stylize(style = 1) |>
  gt::tab_spanner(
    label = "Number of Ages",
    columns = 3:28
  ) |>
  gt::tab_options(
    table.font.size = 8,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

:::

```{r}
#| label: tbl-maturity-samples
#| warning: false
#| echo: false
#| tbl-cap: "Maturity samples collected by the NWFSC West Coast Groundfish Bottom Trawl Survey by year and area where north and south of 36° N. latitude."

maturity_data |>
  dplyr::mutate(
    Area = dplyr::case_when(latitude >= 36 ~ "North", .default = "South")) |>
  dplyr::group_by(year, Area) |>
  dplyr::summarise(
    Samples = dplyr::n()
  ) |>
  tidyr::pivot_wider(
    names_from = Area,
    values_from = Samples,
    names_prefix = "Samples-"
  ) |>
  dplyr::rename(Year = year) |>
  dplyr::ungroup() |>
  gt::gt() |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

 {{< pagebreak >}} 
 
 
## Assessment and Modeling 
 
```{r}
#| label: tbl-model-config
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: !expr if(eval_tables) config_cap

config_table |>
  gt::gt() |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```


```{r}
#| label: tbl-n-param
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: !expr if(eval_tables) parcount_cap

parcount_table |>
  gt::gt() |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

 {{< pagebreak >}} 
 
```{r}
#| label: tbl-data-weights
#| warning: false
#| echo: false
#| tbl-cap: "Data weights from the base model. The data weights for both periods of the Triennial Survey are capped at 1.0 to avoid upweighting these data beyond the number of total samples."

ctl_file[["Variance_adjustment_list"]] |>
  dplyr::select(-factor) |>
  dplyr::mutate(
    fleet = dplyr::case_when(
      fleet == 1 ~ "Trawl",
      fleet == 2 ~ "Hook-and-Line",
      fleet == 3 ~ "Pot",
      fleet == 4 ~ "Trawl Discard",
      fleet == 5 ~ "Hook-and-Line Discard",
      fleet == 6 ~ "Pot Discard",
      fleet == 7 ~ "Early Triennial",
      fleet == 8 ~ "Late Triennial",
      fleet == 9 ~ "NWFSC Slope",
      fleet == 10 ~ "WCGBTS"
    )
  ) |>
  dplyr::rename(
    Fleet = fleet,
    `Data Weight` = value
  ) |>
  gt::gt() |>
  gt::fmt_number(
    columns = 2,
    decimals = 3
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```
 
  {{< pagebreak >}} 

::: {.landscape}

```{r}
#| label: tbl-param
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: !expr if(eval_tables) par_cap 
#| tbl-pos: H

sub_par_table <- par_table[c(1, 23:27, 112:nrow(par_table)), ]
rownames(sub_par_table) <- NULL
kableExtra::kable(
  sub_par_table, 
  format = "latex", 
  longtable = TRUE,
  booktabs = TRUE,
  caption = "Parameter estimates, estimation phase, parameter bounds, estimation status, estimated standard deviation (SD), prior information [distribution(mean, SD)] used in the base model.",
  linesep = "") |>
  kableExtra::column_spec(
    column = c(1, 2, 3, 4, 5, 6, 7),
    width = c("3in", "0.5in", "0.5in", "0.90in", "0.4in", "0.5in", "1.25in")
  ) |>
  kableExtra::kable_styling(
    latex_options = "repeat_header",
    font_size = 8)
```

:::

```{r}
#| label: tbl-likes
#| warning: false
#| echo: false
#| tbl-cap: "Likelihood components by source."

table <- dplyr::bind_cols(
  data.frame(Label = gsub("_", " ", rownames(model_output$likelihoods_used) )), 
  data.frame(Total = model_output$likelihoods_used[,1])
)
table |>
  gt::gt() |>
  gt::fmt_number(
    columns = 2,
    decimals = 1
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

 {{< pagebreak >}} 

```{r, results = "asis"}
#| label: tbl-ref-points
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: !expr if(eval_tables) reference_points_cap 
#| tbl-pos: H

reference_points_table |>
  gt::gt() |>
  gt::fmt_number(
    columns = 2:4,
    rows = c(1:4, 7, 10, 12, 15, 17, 20),
    decimals = 0
  ) |>
  gt::fmt_number(
    columns = 2:4,
    rows = c(5, 8, 9, 13:14, 18:19),
    decimals = 3
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE 
  ) |>  
  gt::tab_style(
    style = list(
      gt::cell_text(style = "italic")
    ),
    locations = gt::cells_body(
      columns = "Reference Point",
      rows = tidyselect::starts_with("Reference")
    )
  ) |>
  gt::sub_missing(
    columns = tidyselect::everything(),
    missing_text = "---"
  ) |>
  gt::as_latex()

```


\pagebreak


```{r, results = "asis"}
#| label: tbl-ts
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: !expr if(eval_tables) time_series_cap 
#| tbl-pos: H

time_series_table |>
  dplyr::rename(
    `Spawning Output (mt)` = `Spawning output`,
    `Stock Status` = `Fraction Unfished`) |>
  dplyr::mutate(
    Year = as.factor(Year),
    `Spawning Output (mt)` = round(`Spawning Output (mt)`, 0),
    `Total Biomass (mt)` = round(`Total Biomass (mt)`, 0),
    `Total Biomass 3+ (mt)` = round(`Total Biomass 3+ (mt)`, 0),
    `Age-0 Recruits (1,000s)` = round(`Age-0 Recruits (1,000s)`, 0),
    `Stock Status` = round(`Stock Status`, 3),
    `Exploitation Rate` = round(`Exploitation Rate`, 3),
    `(1-SPR)/(1-SPR_45%)` = round(`(1-SPR)/(1-SPR_45%)`, 3)
  ) |>
kableExtra::kable(
  format = "latex", 
  longtable = TRUE,
  booktabs = TRUE,
  format.args = list(big.mark = ","),
  caption = "Time series of population estimates from the base model.",
  linesep = "") |>
  kableExtra::kable_styling(
    latex_options = "repeat_header",
    font_size = 8) |>
  kableExtra::column_spec(
    column = 1:9,
    width = "0.5in"
  ) 

```


\pagebreak


::: {.landscape}

```{r, results = "asis"}
#| label: tbl-sens-1
#| warning: false
#| echo: false
#| tbl-cap: "Maximum likelihood estimates for select parameters, derived quantities, reference points, and negative log likelihoods for the base model and alternative sensitivity runs representing the removal of index and age composition data from the NWFSC West Coast Groundfish Bottom Trawl Survey (WCGBTS), the Trienniel Survey, or the NWFSC Slope Survey. Additionally, estimates for the removal of the environmental-based recruitment index are shown."
#| tbl-pos: H

read.csv(here::here("report", "rda", "sens_1_model_para_comp.csv")) |>
  gt::gt() |>
  gt::cols_label(
    Metric = "Metric",
    Base.Model = "Base Model",
    Remove.WCGBTS = "Remove WCGBTS",
    Remove.Triennial = "Remove Triennial",
    Remove.NWFSC.Slope = "Remove NWFSC Slope",
    Remove.Recruitment.Index = "Remove Recruitment Index"
  ) |>
  gt::fmt_number(
    columns = 2:6,
    decimals = 3,
    drop_trailing_zeros = TRUE,
  ) |>
  gt::tab_options(
    table.font.size = 10,
    page.orientation = "landscape",
    latex.use_longtable = TRUE
  ) |>
  gt::sub_missing(
    columns = tidyselect::everything(),
    missing_text = "---"
  ) |>
  gt::cols_width(
    `Metric` ~ px(175),
    tidyselect::starts_with("B") ~ px(120),
    tidyselect::starts_with("R") ~ px(120),
  ) |>
  gt::as_latex()

```

:::

\pagebreak

::: {.landscape}

```{r, results = "asis"}
#| label: tbl-sens-2
#| warning: false
#| echo: false
#| tbl-cap: "Maximum likelihood estimates for select parameters, derived quantities, reference points, and negative log likelihoods for the base model and alternative sensitivity runs representing the use of the McAllister-Ianelli harmonic mean method for weighting composition data, the specifiation of asymptotic selectivity for all NWFSC Surveys, and using the ageing error vector applied in the 2019 stock assessment."
#| tbl-pos: H

read.csv(here::here("report", "rda", "sens_2_model_para_comp.csv")) |>
  dplyr::rename(Metric = X) |>
  gt::gt() |>
  gt::cols_label(
    Base.Model = "Base Model",
    McAllister.Ianelli.Data.Weighting = "McAllister-Ianelli Data Weighting",
    NWFSC.Survey.Asymtotic.Selectivity = "NWFSC Survey Asymptotic Selectivity",
    Ageing.Error.2019.Assessment = "Ageing Error 2019 Assessment"
  ) |>
  gt::fmt_number(
    columns = 2:5,
    decimals = 3,
    drop_trailing_zeros = TRUE,
  ) |>
  gt::tab_options(
    table.font.size = 10,
    page.orientation = "landscape",
    latex.use_longtable = TRUE
  ) |>
  gt::sub_missing(
    columns = tidyselect::everything(),
    missing_text = "---"
  ) |>
  gt::cols_width(
    `Metric` ~ px(175),
    tidyselect::starts_with("B") ~ px(120),
    tidyselect::starts_with("M") ~ px(120),
    tidyselect::starts_with("A") ~ px(120),
    tidyselect::starts_with("N") ~ px(120)
  ) |>
  gt::as_latex()

```

:::

\pagebreak

::: {.landscape}

```{r, results = "asis"}
#| label: tbl-sens-3
#| warning: false
#| echo: false
#| tbl-cap: "Maximum likelihood estimates for select parameters, derived quantities, reference points, and negative log likelihoods for the base model and alternative sensitivity runs representing the estimation of growth (rather than using an empircal weight-at-age approach for growth as in the base model), the estimation of sex-specific natural mortality (*M*), and fixing *M* at the value used in the assessment of sablefish in Alaska, adjusted upwards to offset potential net emigration to Canada, or set to sex-specific values used in the 2019 U.S. West coast assessment of sablefish."
#| tbl-pos: H

read.csv(here::here("report", "rda", "sens_3_model_para_comp.csv")) |>
  gt::gt() |>
  gt::cols_label(
    Base.Model = "Base Model",
    Estimate.Growth = "Estimate Growth",
    M.Sex.Specific = "M Sex-Specific",
    M.Alaska.Assessment = "M Alaska Assessment",
    M.Adjust.For.Migration = "M Adjust For Migration",
    M.Fix.2019.Assessment = "M Fix 2019 Assessment"
  ) |>
  gt::fmt_number(
    columns = 2:7,
    decimals = 3,
    drop_trailing_zeros = TRUE,
  ) |>
  gt::sub_missing(
    columns = tidyselect::everything(),
    missing_text = "---"
  ) |>
  gt::tab_options(
    table.font.size = 10,
    page.orientation = "landscape",
    latex.use_longtable = TRUE
  ) |>
  gt::cols_width(
    #tidyselect::everything() ~ px(150)
    `Metric` ~ px(175),
    tidyselect::starts_with("B") ~ px(100),
    tidyselect::starts_with("E") ~ px(100),
    tidyselect::starts_with("M") ~ px(100)
  ) |>
  gt::as_latex()

```

:::

\pagebreak

::: {.landscape}

```{r, results = "asis"}
#| label: tbl-sens-4
#| warning: false
#| echo: false
#| tbl-cap: "Maximum likelihood estimates for select parameters, derived quantities, reference points, and negative log likelihoods for the base model and alternative sensitivity runs representing the estimaton of steepness (*h*), imposing the restriction that recruitment deviations in the main recruitment period must sum to zero, and estimating early (1890-1974) recruitment deviations with the sum to zero constraint imposed."
#| tbl-pos: H

read.csv(here::here("report", "rda", "sens_4_model_para_comp.csv")) |>
  gt::gt() |>
  gt::cols_label(
    Base.Model = "Base Model",
    Estimate.Steepness = "Estimate Steepness",
    RecDevs.Sum.To.Zero = "RecDevs Sum To Zero",
    Estimate.Early.RecDevs..sum.0. = "Estimate Early RecDevs (Sum 0)"
  ) |>
  gt::fmt_number(
    columns = 2:5,
    decimals = 3,
    drop_trailing_zeros = TRUE,
  ) |>
  gt::tab_options(
    table.font.size = 10,
    page.orientation = "landscape",
    latex.use_longtable = TRUE
  ) |>
  gt::sub_missing(
    columns = tidyselect::everything(),
    missing_text = "---"
  ) |>
  gt::cols_width(
    `Metric` ~ px(175),
    tidyselect::starts_with("B") ~ px(120),
    tidyselect::starts_with("E") ~ px(120),
    tidyselect::starts_with("R") ~ px(120)
  ) |>
  gt::as_latex()

```

:::

\pagebreak

::: {.landscape}

```{r, results = "asis"}
#| label: tbl-sens-5
#| warning: false
#| echo: false
#| tbl-cap: "Maximum likelihood estimates for select parameters, derived quantities, reference points, and negative log likelihoods for the base model and alternative sensitivity runs where discard mortality was increased to 100% for all fleets, discard mortality was increased to 75% for the trawl fishery and 60% for both hook-and-line and pot fisheries, and the pre-1969 catch was doubled."
#| tbl-pos: H

read.csv(here::here("report", "rda", "sens_5_model_para_comp.csv")) |>
  gt::gt() |>
  gt::cols_label(
    X = "Metric",
    Base.Model = "Base Model",
    X100..Discard.Mortality = "100% Discard Mortality",
    X75..TWL...60..HKL.Pot.Discard.Mortality = "75% TWL & 60% HKL/Pot Discard Mortality",
    Double.pre.1969.Catch = "Double Pre-1969 Catch"
  ) |>
  gt::fmt_number(
    columns = 2:5,
    decimals = 3,
    drop_trailing_zeros = TRUE,
  ) |>
  gt::tab_options(
    table.font.size = 10,
    page.orientation = "landscape",
    latex.use_longtable = TRUE
  ) |>
  gt::sub_missing(
    columns = tidyselect::everything(),
    missing_text = "---"
  ) |>
  gt::cols_width(
    tidyselect::starts_with("M") ~ px(175),
    tidyselect::starts_with("B") ~ px(120),
    tidyselect::starts_with("100") ~ px(120),
    tidyselect::starts_with("75") ~ px(120),
    tidyselect::starts_with("D") ~ px(120)
  ) |>
  gt::as_latex()

```

:::

\pagebreak

::: {.landscape}

```{r, results = "asis"}
#| label: tbl-sens-6
#| warning: false
#| echo: false
#| tbl-cap: "Maximum likelihood estimates for the base model and select derived quantities for the base model and alternative sensitivity runs that either increase or decrease the strength of recent (2016-2023) recruitment deviations by 10% in log-space. Sensitivity models were run with all model parameters fixed at the base model maximum likelihood estimates, with the only changes being from the specified adjustments to recent recruitment deviations. Forecast catches in 2025 and 2026 were based on GMT recommendations. The catches from 2027 to 2036 were set equal to the year-specific ABCs. The ABC values were projected using a category 1 time-varying sigma with an initial value of 0.50 in 2027 and a management risk tolerance (P∗) of 0.45."
#| tbl-pos: H

read.csv(here::here("report", "rda", "sens_6_model_para_comp.csv")) |>
  gt::gt() |>
  gt::cols_label(
    X = "Metric",
    Base.Model = "Base Model",
    Increase.Recent.recruitment.strength..10.. = "Increase Recent Recruitment Strength (10%)",
    Decrease.Recent.Recruitment.Strength..10.. = "Decrease Recent Recruitment Strength (10%)"
  ) |>
  gt::fmt_number(
    columns = 2:4,
    decimals = 3,
    drop_trailing_zeros = TRUE,
  ) |>
  gt::tab_options(
    table.font.size = 10,
    page.orientation = "landscape",
    latex.use_longtable = TRUE
  ) |>
  gt::sub_missing(
    columns = tidyselect::everything(),
    missing_text = "---"
  ) |>
  gt::cols_width(
    tidyselect::starts_with("M") ~ px(175),
    tidyselect::starts_with("B") ~ px(150),
    tidyselect::starts_with("I") ~ px(150),
    tidyselect::starts_with("D") ~ px(150)
  ) |>
  gt::as_latex()

```

:::

```{r, results = "asis"}
#| label: tbl-gmt-catch
#| warning: false
#| echo: false
#| tbl-cap: "Removal assumptions in metric tons (mt) provided by the Groundfish Management Team for 2025-2026 by fleet. Removal assumptions were used to project OFLs (mt) and ABCs (mt) for 2027-2036."
#| tbl-pos: H

gmt_catch |>
  dplyr::select(-comment, -Seas) |>
  dplyr::mutate(
    Fleet = dplyr::case_when(
      Fleet == 1 ~ "Trawl",
      Fleet == 2 ~ "Hook-and-Line",
      Fleet == 3 ~ "Pot",
      Fleet == 4 ~ "Trawl Discard",
      Fleet == 5 ~ "Hook-and-Line Discard",
      Fleet == 6 ~ "Pot Discard"
    )
  ) |>
  tidyr::pivot_wider(
    names_from = Fleet,
    values_from = `dead(B)`
  ) |>
  dplyr::relocate(`Total Catch`, .after = `Pot Discard`) |>
  gt::gt() |>
  gt::fmt_number(
    columns = c(2:8),
    decimals = 1
  ) |>
  gt::cols_width(
    tidyselect::everything() ~ px(70)
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE 
  ) |>
  gt::as_latex()

```

::: {.landscape}

```{r, results = "asis"}
#| label: tbl-projections
#| warning: false
#| echo: false
#| tbl-cap:  "Potential OFLs (mt), ABCs (mt), ACLs (mt), the buffer between the OFL and ABC, estimated spawning output,and stock status with adopted OFLs and ACLs and assumed catch for the first two years of the projection period (2025-2026). Projections were conducted assuming a category 1 time-varying sigma of 0.50 and a P$^*$ of 0.45."
#| tbl-pos: H

projections_table |>
  dplyr::rename(
    `Stock Status` = `Fraction Unfished`,
    `Spawning Output (mt)` = `Spawning output`
  ) |>
  gt::gt() |>
  gt::fmt_number(
    columns = c(2:5, 7:9),
    decimals = 0
  ) |>
  gt::fmt_number(
    columns = c(6, 10),
    decimals = 3
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE 
  ) |>
  gt::sub_missing(
    columns = tidyselect::everything(),
    missing_text = "---"
  ) |>
  gt::cols_align(
    align = "center"
  ) |>
  gt::cols_width(
    tidyselect::everything() ~ px(75)
  ) |>
  gt::as_latex()

```

:::

```{r, results = "asis"}
#| label: tbl-decision-table
#| warning: false
#| echo: false
#| tbl-cap: "Decision table summary of 10 year projections beginning in 2027 for alternative states of nature based on an axis of uncertainty about natural mortality for the base model. Columns range over low, base, and high states of nature and rows range over different catch level assumptions. The base model estimated natural mortality of 0.088 yr$^{-1}$ for females and males. The low state of nature assumed a natural mortality of 0.095 yr$^{-1}$ and the high state of nature assumed a natural mortality of 0.070 yr$^{-1}$ for both sexes. Catch in 2025 and 2026 were based upon removal assumptions provided by the GMT."
#| tbl-pos: H

 table_decision(
    list(low, base, high),
    list(low_40, base_40, high_40),
    years = 2025:2036,
    format = c("latex"),
    caption = formals(kableExtra::kbl)$caption,
    label = formals(kableExtra::kbl)$label,
    digits = c(0, 0, 3),
    tex = TRUE)
```

 {{< pagebreak >}}

```{r, results = "asis"}
#| label: tbl-risk-table
#| warning: false
#| echo: false
#| tbl-cap: "Risk table for sablefish to document ecosystem and environmental factors potentially affecting stock productivity and uncertainty or other concerns arising from the stock assessment. Level 1 is a favorable ranking, Level 2 neutral, and Level 3 unfavorable."
#| tbl-pos: H

risk <- read.csv(here::here("report", "rda", "RiskTable.csv") )
risk|>
  gt::gt() |>
  gt::tab_options(
    table.font.size = 8,
    latex.use_longtable = TRUE
  ) |>
  gt::cols_label(
    Ecosystem.and.environmental.conditions = "Ecosystem and Environmental Conditions",
    Assessment.data.inputs = "Assessment Data Inputs",
    Assessment.model.fits.and.structural.uncertainty = "Assessment Model Fits and Structural Uncertainty"
  ) |>
  gt::cols_width(
    everything() ~ px(190)
  ) |>
  gt::as_latex()
```

 {{< pagebreak >}}

```{r, results = "asis"}
#| label: tbl-risk-table-projections
#| warning: false
#| echo: false
#| tbl-cap: "Theoretical OFLs (mt), ABCs (mt), ACLs (mt), the buffer between the OFL and ABC, estimated spawning output (mt), stock status, and assumed catch for the first two years of the projection period (2025-2026). Projections were conducted assuming a time-varying sigma of 0.25 and a P$^*$ of 0.45."
#| tbl-pos: H

rt_projections_table |>
  dplyr::rename(
    `Stock Status` = `Fraction Unfished`,
    `Spawning Output (mt)` = `Spawning output`
  ) |>
  gt::gt() |>
  gt::fmt_number(
    columns = c(2:3, 5:7),
    decimals = 0
  ) |>
  gt::fmt_number(
    columns = c(4, 8),
    decimals = 3
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE 
  ) |>
  gt::sub_missing(
    columns = tidyselect::everything(),
    missing_text = "---"
  ) |>
  gt::cols_align(
    align = "center"
  ) |>
  gt::cols_width(
    everything() ~ px(75)
  ) |>
  gt::as_latex()

```