---
title: 'Status of the sablefish (*Anoplopoma fimbria*) off the U.S. West Coast in 2025'
author:
  - name: 'Chantel R. Wetzel'
    affiliations:
      - name: 'NOAA Fisheries Northwest Fisheries Science Center'
        address: '2725 Montlake Boulevard East'
        city: 'Seattle'
        state: 'WA'
        postal-code: '98112-2097'
  - name: 'Aaron M. Berger'
    affiliations:
      - name: 'NOAA Fisheries Northwest Fisheries Science Center'
        address: '2032 SE OSU Drive Building 955'
        city: 'Newport'
        state: 'OR'
        postal-code: '97365-2097'
  - name: 'Cheryl Barnes'
    affiliations: 
      - name: 'University of Oregon'
        address: 'ADD'
        city: 'Corvalis'
        state: 'OR'
        postal-code: 'ADD'
  - name: 'Joshua A. Zahner'
    affiliations:
      - name: 'University of Alaska Fairbanks'
        address: 'Department of Fisheries at Lena Point, College of Fisheries and Ocean Sciences, University of Alaska Fairbanks, 17101 Point Lena Loop Rd'
        city: 'Juneau'
        state: 'AK'
        postal-code: '99801'
  - name: 'Nick Tolimieri'
    affiliations:
      - name: 'NOAA Fisheries Northwest Fisheries Science Center'
        address: '2725 Montlake Boulevard East'
        city: 'Seattle'
        state: 'WA'
        postal-code: '98112-2097'
date: today
lang: en 
keep-tex: true 
cover: 
pdf-engine: lualatex
format: 
  pdf: 
    documentclass: scrartcl
    number-sections: true
    template-partials:
      - 'support_files/before-body.tex'
      - 'support_files/_titlepage.tex'
    include-in-header:
      - 'support_files/in-header.tex'
      - 'support_files/figures.tex'
      - 'support_files/pfmc.tex'
    toc: true
    lof: false
    lot: false
    titlepage-geometry: 
      - top=2in
      - bottom=1in
      - right=1in
      - left=1in
output-file: 'sablfefish_SAR_2025' 
params:
   office: 'NWFSC'
   species: 'sablfefish'
   spp_latin: 'Anoplopoma fimbria'
   region: 'U.S. West Coast'
bibliography: 
-  asar_references.bib 
---


\pagenumbering{roman}
\setcounter{page}{1}

\renewcommand{\thetable}{\roman{table}}
\renewcommand{\thefigure}{\roman{figure}}


```{r, results='asis'}
#| label: 'load_packages'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('001_load_packages.qmd', quiet = TRUE)
cat(a, sep = '\n')
```



```{r} 
#| label: 'output_and_quantities'
#| echo: false 
#| warning: false 
#| eval: true 

spp <- "sablefish"
Spp <- "Sablefish"

# Define the location and name of the base model
model_name <- "13_m_prior"
model_dir <- here::here("model", "_bridging", model_name)
load(file.path(model_dir, "model_output.rda"))
# Directory for tables created by r4ss::table_exec_summary()
table_dir <- file.path(model_dir, "tables")
# Other potential directories that could be useful
sens_dir <-  here::here("model", "sensitivities")
retro_dir <- profile_dir <- here::here("model")

# Define objects from the list created by r4ss::SS_output
end_year <- model_output$endyr + 1
data_end_year <- model_output$endyr
start_year <- model_output$startyr
all_years <- start_year:end_year
proj_years <- (end_year + 2):(end_year + 12)
es_10_years <- (end_year - 10):data_end_year
es_12_years <- (end_year - 10):(end_year + 1)

# Define some derived quantities
sb <- model_output$derived_quants[model_output$derived_quants$Label %in% paste0("SSB_", all_years), "Value"]
sb0 <- model_output$derived_quants[model_output$derived_quants$Label == "SSB_Virgin", "Value"] 
depl <- round(sb / sb0, 3)
quants <- data.frame(
  year = all_years, 
  sb = round(sb, 0), 
  depl = depl)

depl_final <- quants[quants$year == end_year, 'depl']
quants[, "sb"] <- format(round(quants[, "sb"], 0), scientific = FALSE, big.mark = ",")
sb_final <- quants[quants$year == end_year, 'sb'] 
min_sb <- min(quants[, "sb"])
min_sb_year <- quants[quants$sb == min_sb, 'year']

min_depl <- min(quants$depl)
min_depl_year <- quants[quants$depl == min_depl, 'year']

catch_spr <- model_output$derived_quants |>
  dplyr::filter(Label == "Dead_Catch_SPR") |>
  dplyr::mutate(
    catch_spr = round(Value, 0)
  ) |>
  dplyr::select(catch_spr) |>
  as.numeric() |>
  format(scientific = FALSE, big.mark = ",")

sb_spr <- model_output$derived_quants |>
  dplyr::filter(Label == "SSB_Btgt") |>
  dplyr::mutate(
    sb_spr = round(Value, 0)
  ) |>
  dplyr::select(sb_spr) |>
  as.numeric() |>
  format(scientific = FALSE, big.mark = ",")

# Calculated harvest metrics
est_ofl <- round(model_output$derived_quants[model_output$derived_quants$Label %in% paste0("OFLCatch_", proj_years), "Value"], 0) 
est_abc <- round(model_output$derived_quants[model_output$derived_quants$Label %in% paste0("ForeCatch_", proj_years), "Value"], 0) 

# Parameter values
recdevs <- dplyr::bind_rows(
  model_output$parameters |>
    dplyr::filter(grepl("Main_RecrDev", Label)) |>
    dplyr::select(Value),
  model_output$parameters |>
    dplyr::filter(grepl("Late_RecrDev", Label)) |>
    dplyr::select(Value)
  )
rec_years <- readr::parse_number(rownames(recdevs))
recdevs <- data.frame(
  years = rec_years,
  recdevs = recdevs$Value
)
high_5 <- sort(recdevs[, "recdevs"], decreasing = TRUE, index.return = TRUE)$ix[1:5]
top_recdevs <- recdevs[high_5, ]
low_5 <- sort(recdevs[, "recdevs"], decreasing = FALSE, index.return = TRUE)$ix[1:5]
low_recdevs <- recdevs[low_5, ]

# Parameters: biology values
m <- model_output$parameters |>
  dplyr::filter(Label %in% c("NatM_uniform_Fem_GP_1", "NatM_uniform_Mal_GP_1")) |>
  dplyr::select(Label, Value) |>
  tidyr::pivot_wider(
    names_from = Label,
    values_from = Value
  ) |>
  as.numeric()
h <- model_output$parameters |>
  dplyr::filter(Label %in% c("SR_BH_steep")) |>
  dplyr::select(Value) |>
  as.numeric()
Linf <- model_output$parameters |>
  dplyr::filter(Label %in% c("L_at_Amax_Fem_GP_1", "L_at_Amax_Mal_GP_1")) |>
  dplyr::select(Label, Value) |>
  tidyr::pivot_wider(
    names_from = Label,
    values_from = Value
  ) |>
  as.numeric() |>
  round(1)
Lmin <- model_output$parameters |>
  dplyr::filter(Label %in% c("L_at_Amin_Fem_GP_1", "L_at_Amin_Mal_GP_1")) |>
  dplyr::select(Label, Value) |>
  tidyr::pivot_wider(
    names_from = Label,
    values_from = Value
  ) |>
  as.numeric() |>
  round(1)
k <- model_output$parameters |>
  dplyr::filter(Label %in% c("VonBert_K_Fem_GP_1", "VonBert_K_Mal_GP_1")) |>
  dplyr::select(Label, Value) |>
  tidyr::pivot_wider(
    names_from = Label,
    values_from = Value
  ) |>
  as.numeric() |>
  round(3)

# Survey catchabilities and added sd
find <- grep("LnQ_base", model_output$parameters$Label)
q <- model_output$parameters[find, ] |>
  dplyr::select(Label, Value) 
rownames(q) <- NULL
q[, "Value"] <- exp(q[, "Value"])
find <- grep("Q_extraSD", model_output$parameters$Label)
survey_add_sd <- model_output$parameters[find, ] |>
  dplyr::select(Label, Value) 
rownames(survey_add_sd) <- NULL

ofl_sigma <- round(model_output$OFL_sigma, 2)
sb_sigma <- round(model_output$Pstar_sigma,2)

# Read in adopted harvest specifications:
cw_harvest_spex <- read.csv(here::here("data-processed", "harvest_spex.csv")) |>
  dplyr::filter(AREA_NAME == "CW", YEAR %in% es_12_years) |>
  dplyr::mutate(
    VAL = round(VAL, 0)
  )
area_harvest_spex <- read.csv(here::here("data-processed", "harvest_spex.csv")) |>
  dplyr::filter(AREA_NAME != "CW", YEAR %in% es_12_years) |>
  dplyr::mutate(
    VAL = round(VAL, 0)
  )

``` 

{{< pagebreak >}} 

Please cite this publication as: 

Wetzel, C.R., A.M. Berger, C. Barnes, J.A. Zahner, N. Tolimieri. 2025. Status of the sablefish (*Anoplopoma fimbria*) off the U.S. West Coast in 2025. Pacific Fisheries Management Council, Portland, Oregon.

 {{< pagebreak >}} 


```{r, results='asis'}
#| label: 'load_tables'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('002_load_tables.qmd', quiet = TRUE)
cat(a, sep = '\n')
```


```{r, results='asis'}
#| label: 'disclaimer'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('00a_disclaimer.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'executive_summary'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('01_executive_summary.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'introduction'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('02_introduction.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'data'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('03_data.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'assessment-configuration'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('04a_assessment-configuration.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'assessment-results'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('04b_assessment-results.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'assessment-sensitivity'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('04c_assessment-sensitivity.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 
 

```{r, results='asis'}
#| label: 'management'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('05_management.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'acknowledgments'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('06_acknowledgments.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'references'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('07_references.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'tables'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('08_tables.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'figures'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('09_figures.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'notes'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('10_notes.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'appendix'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('11_appendix.qmd', quiet = TRUE)
cat(a, sep = '\n')
```
