library(dplyr)
library(ggplot2)
library(pacfintools)
library(r4ss)

base <- SS_output(dir=here::here("model","base_model","8.36_base_model"))
Wt_age_vector<- SS_output(dir=here::here("model","_star_requests","8.36_WtAgeVector"))
mymodels <- list(base,Wt_age_vector)
mysummary <- SSsummarize(mymodels)
modelnames <- c("Base Model","Stationary Weight-at-age")
pdf(here::here("model","_star_requests","8.36_WtAgeVector","Compare_models.pdf"))
SSplotComparisons(mysummary, legendlabels=modelnames,plotdir=here::here("model","_star_requests","8.36_WtAgeVector"),print=TRUE,endyr=2025,new=F,densitynames = c("SPB_Virgin","R0"))
dev.off()
dev.off()
SS_plots(Wt_age_vector)