library(dplyr)
library(ggplot2)
library(pacfintools)
library(r4ss)

base <- SS_output(dir=here::here("model","base_model","8.36_base_model"))
HistCatch<- SS_output(dir=here::here("model","_star_requests","IncreaseHistoricalCatch"))
mymodels <- list(base,HistCatch)
mysummary <- SSsummarize(mymodels)
modelnames <- c("Base Model","Double Historical (pre-1969) Catch")
pdf(here::here("model","_star_requests","IncreaseHistoricalCatch","Compare_models.pdf"))
SSplotComparisons(mysummary, legendlabels=modelnames,plotdir=here::here("model","_star_requests","IncreaseHistoricalCatch"),print=TRUE,endyr=2025,new=F,densitynames = c("SPB_Virgin","R0"))
dev.off()
dev.off()
SS_plots(HistCatch)