library(dplyr)
library(ggplot2)
library(pacfintools)
library(r4ss)

base <- SS_output(dir=here::here("model","base_model","8.36_base_model"))
reduce_effN<- SS_output(dir=here::here("model","_star_requests","DownweightAges"))
mymodels <- list(base,reduce_effN)
mysummary <- SSsummarize(mymodels)
modelnames <- c("Base Model","reduce_effN_90%")
pdf(here::here("model","_star_requests","DownweightAges","Compare_models.pdf"))
SSplotComparisons(mysummary, legendlabels=modelnames,plotdir=here::here("model","_star_requests","DownweightAges"),print=TRUE,endyr=2025,new=F,densitynames = c("SPB_Virgin","R0"))
dev.off()
dev.off()
SS_plots(reduce_effN)